const base=import.meta.env.VITE_API_BASE_URL?.replace(/\/$/,'')??'https://localhost:7001';
export type AgentRole='Planner'|'Coder'|'Reviewer';export type ModelSource='ProjectOverride'|'GlobalDefault'|'EnvironmentFallback'|'Unconfigured';
export interface AiModel{id:string;displayName:string;provider:string;modelIdentifier:string;description?:string;isEnabled:boolean;providerSupported:boolean;createdAtUtc:string;updatedAtUtc:string}
export interface Assignment{agentRole:AgentRole;projectId?:string;aiModelProfileId:string;displayName:string;provider:string;modelIdentifier:string}
export interface EffectiveModel{agentRole:AgentRole;provider?:string;modelIdentifier?:string;modelDisplayName?:string;aiModelProfileId?:string;source:ModelSource;modelEnabled:boolean;providerSupported:boolean;operational:boolean;message:string}
async function request<T>(path:string,init?:RequestInit){const response=await fetch(`${base}${path}`,{...init,headers:{'Content-Type':'application/json',...init?.headers}});if(!response.ok){const body=await response.json().catch(()=>null) as {message?:string}|null;throw new Error(body?.message??`Request failed (${response.status}).`)}if(response.status===204)return undefined as T;return response.json() as Promise<T>}
export const modelKeys={models:['ai-models'] as const,global:['ai-role-assignments'] as const,effective:(projectId:string)=>['project-effective-models',projectId] as const};
export const listModels=()=>request<AiModel[]>('/api/ai/models');export const saveModel=(input:Partial<AiModel>&{displayName:string;provider:string;modelIdentifier:string},id?:string)=>request<AiModel>(id?`/api/ai/models/${id}`:'/api/ai/models',{method:id?'PUT':'POST',body:JSON.stringify(input)});export const setModelEnabled=(id:string,isEnabled:boolean)=>request<AiModel>(`/api/ai/models/${id}/status`,{method:'PATCH',body:JSON.stringify({isEnabled})});
export const listGlobalAssignments=()=>request<Assignment[]>('/api/ai/role-assignments');export const setGlobalAssignment=async(role:AgentRole,id:string)=>{await request<Assignment>(`/api/ai/role-assignments/${role}`,{method:'PUT',body:JSON.stringify({aiModelProfileId:id})})};export const removeGlobalAssignment=(role:AgentRole)=>request<void>(`/api/ai/role-assignments/${role}`,{method:'DELETE'});
export const getEffectiveModels=(projectId:string)=>request<EffectiveModel[]>(`/api/projects/${projectId}/ai/role-assignments`);export const setProjectAssignment=async(projectId:string,role:AgentRole,id:string)=>{await request<Assignment>(`/api/projects/${projectId}/ai/role-assignments/${role}`,{method:'PUT',body:JSON.stringify({aiModelProfileId:id})})};export const removeProjectAssignment=(projectId:string,role:AgentRole)=>request<void>(`/api/projects/${projectId}/ai/role-assignments/${role}`,{method:'DELETE'});
