import { createBrowserRouter, Navigate } from 'react-router-dom';
import { AppLayout } from '../layouts/AppLayout';
import { CreateProjectPage, ProjectHealthPage, ProjectSettingsPage, ProjectsPage } from '../features/projects/pages/ProjectsPages';
import { ProjectWorkspaceLayout } from '../features/projects/layouts/ProjectWorkspaceLayout';
import { ProjectOverviewPage } from '../features/projects/pages/ProjectOverviewPage';
import { ProjectDeliveryPage } from '../features/projects/pages/ProjectDeliveryPage';
import { ProjectQualityPage } from '../features/projects/pages/ProjectQualityPage';
import { CreateRunPage, RunsPage } from '../features/runs/pages/RunPages';
import { RunDetailLayout } from '../features/runs/layouts/RunDetailLayout';
import { RunOverview } from '../features/runs/pages/RunOverview';
import { RunTasks } from '../features/runs/pages/RunTasks';
import { RunActivity } from '../features/runs/pages/RunActivity';
import { RunAiTelemetry } from '../features/runs/pages/RunAiTelemetry';
import { RunDelivery } from '../features/runs/pages/RunDelivery';
import { AiProvidersPage } from '../features/ai/pages/AiProvidersPage';
export const router=createBrowserRouter([{path:'/',element:<AppLayout/>,children:[{index:true,element:<Navigate to="/projects" replace/>},{path:'ai-providers',element:<AiProvidersPage/>},{path:'projects',element:<ProjectsPage/>},{path:'projects/new',element:<CreateProjectPage/>},{path:'projects/:projectId',element:<ProjectWorkspaceLayout/>,children:[{index:true,element:<Navigate to="dashboard" replace/>},{path:'dashboard',element:<ProjectOverviewPage/>},{path:'delivery',element:<ProjectDeliveryPage/>},{path:'quality',element:<ProjectQualityPage/>},{path:'settings',element:<ProjectSettingsPage/>},{path:'health',element:<ProjectHealthPage/>},{path:'runs',element:<RunsPage/>},{path:'runs/new',element:<CreateRunPage/>},{path:'runs/:pipelineRunId',element:<RunDetailLayout/>,children:[{index:true,element:<Navigate to="overview" replace/>},{path:'overview',element:<RunOverview/>},{path:'tasks',element:<RunTasks/>},{path:'activity',element:<RunActivity/>},{path:'ai-telemetry',element:<RunAiTelemetry/>},{path:'delivery',element:<RunDelivery/>}]}]}]}]);
