using System.Text.Json;
using Impersonate.Domain.Ai;
namespace Impersonate.Application.Ai;
internal sealed class AiProviderConnectionService(IAiRoutingRepository repository, IProviderCredentialStore credentials, IEnumerable<IAiProviderAdapter> adapters) : IAiProviderConnectionService
{
 public async Task<IReadOnlyList<ProviderConnectionDto>> ListAsync(CancellationToken ct)=>(await repository.GetConnectionsAsync(ct)).Select(Map).ToList();
 public async Task<ProviderConnectionDto> CreateAsync(ProviderType type,CreateProviderConnectionRequest request,CancellationToken ct){var c=AiProviderConnection.Create(type,request.DisplayName);await repository.AddConnectionAsync(c,ct);await repository.SaveChangesAsync(ct);await credentials.StoreAsync(c.Id,new(request.ApiKey,request.Organisation,request.Project),ct);return Map(c);}
 public async Task<ProviderConnectionDto?> ValidateAsync(Guid id,CancellationToken ct){var c=await repository.GetConnectionAsync(id,ct);if(c is null)return null;var secret=await credentials.RetrieveAsync(id,ct);if(secret is null){c.ValidationFailed(true,"credentials_missing","No saved credentials are available.");await repository.SaveChangesAsync(ct);return Map(c);}var r=await Adapter(c.ProviderType).ValidateAsync(new(id,c.ProviderType,secret),ct);if(r.Succeeded)c.Connected();else c.ValidationFailed(r.InvalidCredentials,r.FailureCode??"provider_unavailable",r.SafeMessage);await repository.SaveChangesAsync(ct);return Map(c);}
 public async Task<ProviderConnectionDto?> SynchroniseAsync(Guid id,CancellationToken ct){var c=await repository.GetConnectionAsync(id,ct);if(c is null)return null;if(c.Status!=ProviderConnectionStatus.Connected)throw new InvalidOperationException("Only connected providers can synchronise models.");var secret=await credentials.RetrieveAsync(id,ct)??throw new InvalidOperationException("Saved credentials are unavailable.");var found=await Adapter(c.ProviderType).DiscoverModelsAsync(new(id,c.ProviderType,secret),ct);var existing=(await repository.GetModelsAsync(id,ct)).ToDictionary(x=>x.ProviderModelId,StringComparer.Ordinal);foreach(var x in existing.Values)x.MarkUnavailable();foreach(var x in found.GroupBy(x=>x.Id,StringComparer.Ordinal).Select(x=>x.First())){var caps=JsonSerializer.Serialize((int)x.Capabilities);if(existing.TryGetValue(x.Id,out var model))model.Refresh(x.Name,x.Description,x.Lifecycle,x.CapabilitySource,caps,x.ContextWindow,x.MaximumOutput);else await repository.AddModelAsync(DiscoveredModel.Create(id,c.ProviderType,x.Id,x.Name,x.Description,x.Lifecycle,x.CapabilitySource,caps,x.ContextWindow,x.MaximumOutput),ct);}c.Synchronised();await repository.SaveChangesAsync(ct);return Map(c);}
 public async Task<IReadOnlyList<DiscoveredModelDto>?> ModelsAsync(Guid id,CancellationToken ct){if(await repository.GetConnectionAsync(id,ct) is null)return null;return (await repository.GetModelsAsync(id,ct)).Select(Map).ToList();}
 public async Task<bool> DisableAsync(Guid id,CancellationToken ct){var c=await repository.GetConnectionAsync(id,ct);if(c is null)return false;c.Disable();await repository.SaveChangesAsync(ct);return true;}
 public async Task<bool> RemoveAsync(Guid id,CancellationToken ct){var c=await repository.GetConnectionAsync(id,ct);if(c is null)return false;await credentials.DeleteAsync(id,ct);c.Disable();await repository.SaveChangesAsync(ct);return true;}
 private IAiProviderAdapter Adapter(ProviderType type)=>adapters.Single(x=>x.ProviderType==type);
 private static ProviderConnectionDto Map(AiProviderConnection x)=>new(x.Id,x.ProviderType,x.DisplayName,x.Status,x.LastValidatedAtUtc,x.LastModelSyncAtUtc,x.Models.Count(m=>m.IsAvailable),x.LastFailureCode,x.LastSafeFailureMessage);
 private static DiscoveredModelDto Map(DiscoveredModel x)=>new(x.Id,x.ProviderConnectionId,x.ProviderType,x.ProviderModelId,x.DisplayName,x.Description,x.LifecycleStatus,x.IsAvailable,x.ContextWindowSize,x.MaximumOutputSize);
}
