using System.Diagnostics;
using System.Text;
using Impersonate.Application.Execution;
using Microsoft.Extensions.Options;
using Microsoft.Extensions.Logging;

namespace Impersonate.Infrastructure.Execution;

internal sealed class RepositoryWorkspaceService:IRepositoryWorkspaceService
{
    private const string Prefix="workspace:";private readonly string root;private readonly IExecutionArtifactStore artifacts;private readonly SafeProcess processes;private readonly int outputLimit,maximumAttempts;
    public RepositoryWorkspaceService(IOptions<ExecutionOptions> options,IExecutionArtifactStore artifacts,SafeProcess processes){root=Path.GetFullPath(options.Value.WorkspaceRoot??Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"Impersonate","workspaces"));this.artifacts=artifacts;this.processes=processes;outputLimit=options.Value.MaximumToolOutputCharacters;maximumAttempts=options.Value.MaximumWorkspacePreparationAttempts;Directory.CreateDirectory(root);}
    public async Task<WorkspacePreparationResult> PrepareAsync(WorkspaceRequest request,CancellationToken ct)
    {
        var relative=Path.Combine(request.ProjectId.ToString("N"),request.PipelineRunId.ToString("N"),request.PlannedTaskId.ToString("N"),request.AttemptNumber.ToString());var path=Resolve(relative);
        try
        {
            if(Directory.Exists(path))Directory.Delete(path,true);Directory.CreateDirectory(Path.GetDirectoryName(path)!);
            ProcessResult clone=default!;WorkspaceFailure failure=default!;for(var attempt=1;attempt<=maximumAttempts;attempt++){clone=await processes.RunAsync("git",["-c","core.longpaths=true","clone","--no-tags","--single-branch","--branch",request.DefaultBranch,"--",request.RepositoryUrl,path],root,300,outputLimit,null,ct);if(clone.Succeeded)break;failure=Classify(clone);if(!failure.Transient||attempt==maximumAttempts)return new(false,null,failure.Code,failure.Message);if(Directory.Exists(path))Directory.Delete(path,true);await Task.Delay(TimeSpan.FromMilliseconds(200*Math.Pow(2,attempt-1)),ct);}
            foreach(var reference in request.ApprovedPatchReferences.Concat(request.CurrentPatchReference is null?[]:[request.CurrentPatchReference])){var patch=await artifacts.ReadTextAsync(reference,2_000_000,ct);var applied=await processes.RunAsync("git",["-c","core.longpaths=true","apply","--whitespace=nowarn","-"],path,120,outputLimit,patch,ct);if(!applied.Succeeded)return new(false,null,"workspace_preparation_failed","An approved patch could not be applied to the isolated workspace.");}
            return new(true,new(Prefix+relative.Replace('\\','/')),null,null);
        }
        catch(UnauthorizedAccessException){return new(false,null,"workspace_access_denied","The configured workspace root is not accessible.");}
        catch(Exception ex) when(ex is IOException or InvalidOperationException){return new(false,null,"execution_environment_invalid","The sanitized execution environment could not prepare the workspace root.");}
    }
    public Task CleanupAsync(WorkspaceReference workspace,CancellationToken ct){ct.ThrowIfCancellationRequested();var path=FromReference(workspace);if(Directory.Exists(path))Directory.Delete(path,true);return Task.CompletedTask;}
    internal string FromReference(WorkspaceReference reference){if(!reference.Value.StartsWith(Prefix,StringComparison.Ordinal))throw new ArgumentException("Workspace reference is invalid.");return Resolve(reference.Value[Prefix.Length..].Replace('/',Path.DirectorySeparatorChar));}
    private string Resolve(string relative){if(Path.IsPathRooted(relative)||relative.Split(Path.DirectorySeparatorChar,Path.AltDirectorySeparatorChar).Contains(".."))throw new ArgumentException("Workspace path is invalid.");var path=Path.GetFullPath(Path.Combine(root,relative));if(!path.StartsWith(root+Path.DirectorySeparatorChar,StringComparison.OrdinalIgnoreCase))throw new ArgumentException("Workspace path escapes the configured root.");return path;}
    private static string Safe(string value)=>value.Length<=1000?value:value[..1000];
    private static WorkspaceFailure Classify(ProcessResult result){if(result.StartFailure)return new("git_not_available","Git could not be started in the sanitized execution environment.",false);if(result.TimedOut)return new("workspace_clone_timeout","The isolated repository clone timed out.",true);var text=result.Output.ToLowerInvariant();if(text.Contains("getaddrinfo")||text.Contains("could not resolve host")||text.Contains("name or service not known"))return new("repository_dns_failed","Repository DNS resolution failed while preparing the isolated workspace.",true);if(text.Contains("authentication failed")||text.Contains("could not read username")||text.Contains("terminal prompts disabled")||text.Contains("permission denied (publickey)"))return new("repository_authentication_required","Repository authentication is required.",false);if(text.Contains("remote branch")&&text.Contains("not found")||text.Contains("couldn't find remote ref"))return new("repository_branch_not_found","The configured repository branch was not found.",false);if(text.Contains("access is denied")||text.Contains("permission denied"))return new("workspace_access_denied","The configured workspace root is not accessible.",false);if(text.Contains("repository not found"))return new("repository_unavailable","The configured repository is unavailable.",false);if(text.Contains("unable to access")||text.Contains("failed to connect")||text.Contains("connection"))return new("repository_unavailable","The configured repository is temporarily unavailable.",true);return new("workspace_preparation_failed","The isolated repository workspace could not be prepared.",false);}
    private sealed record WorkspaceFailure(string Code,string Message,bool Transient);
}

internal sealed class SafeRepositoryTools(RepositoryWorkspaceService workspaces,IOptions<ExecutionOptions> options,SafeProcess processes):IRepositoryTools
{
    private static readonly HashSet<string> Executables=new(StringComparer.OrdinalIgnoreCase){"dotnet","node","npm","npx","git"};
    private static readonly HashSet<string> GitCommands=new(StringComparer.OrdinalIgnoreCase){"status","diff","apply","rev-parse","ls-files","checkout","clone"};
    private readonly int limit=options.Value.MaximumToolOutputCharacters;
    public Task<RepositoryToolResult> ListFilesAsync(WorkspaceReference workspace,string relativePath,CancellationToken ct){var root=workspaces.FromReference(workspace);var path=Resolve(root,relativePath,true);var files=Directory.EnumerateFiles(path,"*",SearchOption.AllDirectories).Where(x=>!x.Contains($"{Path.DirectorySeparatorChar}.git{Path.DirectorySeparatorChar}")).Take(1000).Select(x=>Path.GetRelativePath(root,x).Replace('\\','/'));return Task.FromResult(Ok(string.Join('\n',files)));}
    public async Task<RepositoryToolResult> ReadFileAsync(WorkspaceReference workspace,string relativePath,CancellationToken ct){var root=workspaces.FromReference(workspace);if(IsSensitive(relativePath))return Fail("tool_rejected","Credential and repository metadata files cannot be read.");var path=Resolve(root,relativePath,false);var info=new FileInfo(path);if(info.Length>1_000_000)return Fail("tool_rejected","File exceeds the read limit.");var bytes=await File.ReadAllBytesAsync(path,ct);if(bytes.AsSpan().IndexOf((byte)0)>=0)return Fail("tool_rejected","Binary files are not supported.");return Ok(Bound(Encoding.UTF8.GetString(bytes),out var truncated),truncated);}
    public async Task<RepositoryToolResult> SearchTextAsync(WorkspaceReference workspace,string query,string relativePath,CancellationToken ct){if(string.IsNullOrWhiteSpace(query))return Fail("tool_rejected","Search query is required.");var root=workspaces.FromReference(workspace);var path=Resolve(root,relativePath,true);var results=new List<string>();foreach(var file in Directory.EnumerateFiles(path,"*",SearchOption.AllDirectories).Where(x=>!x.Contains($"{Path.DirectorySeparatorChar}.git{Path.DirectorySeparatorChar}"))){ct.ThrowIfCancellationRequested();if(new FileInfo(file).Length>1_000_000)continue;string text;try{text=await File.ReadAllTextAsync(file,ct);}catch{continue;}var lines=text.Split('\n');for(var i=0;i<lines.Length&&results.Count<200;i++)if(lines[i].Contains(query,StringComparison.OrdinalIgnoreCase))results.Add($"{Path.GetRelativePath(root,file).Replace('\\','/')}:{i+1}:{lines[i].TrimEnd()}");if(results.Count>=200)break;}return Ok(Bound(string.Join('\n',results),out var truncated),truncated);}
    public async Task<RepositoryToolResult> ApplyPatchAsync(WorkspaceReference workspace,string patch,CancellationToken ct){if(string.IsNullOrWhiteSpace(patch)||patch.IndexOf('\0')>=0)return Fail("tool_rejected","A UTF-8 text patch is required.");if(patch.Contains("GIT binary patch",StringComparison.Ordinal)||patch.Contains("Binary files ",StringComparison.Ordinal))return Fail("tool_rejected","Binary patches are not supported.");if(patch.Contains("../",StringComparison.Ordinal)||patch.Contains("..\\",StringComparison.Ordinal))return Fail("tool_rejected","Patch traversal is not permitted.");var result=await processes.RunAsync("git",Git(["apply","--whitespace=nowarn","-"]),workspaces.FromReference(workspace),120,limit,patch,ct);return result.Succeeded?Ok(result.Output):Fail("tool_rejected",Bound(result.Output,out _));}
    public async Task<RepositoryToolResult> GetDiffAsync(WorkspaceReference workspace,CancellationToken ct){var root=workspaces.FromReference(workspace);var intent=await processes.RunAsync("git",Git(["add","--intent-to-add","--","."]),root,120,limit,null,ct);if(!intent.Succeeded)return Fail("patch_generation_failed",intent.Output);var result=await processes.RunAsync("git",Git(["diff","--no-ext-diff","--"]),root,120,limit,null,ct);if(result.Output.Contains("GIT binary patch",StringComparison.Ordinal)||result.Output.Contains("Binary files ",StringComparison.Ordinal))return Fail("patch_generation_failed","Binary patches are not supported.");return result.Succeeded?Ok(Bound(result.Output,out var truncated),truncated):Fail("patch_generation_failed",result.Output);}
    public async Task<RepositoryToolResult> RunCommandAsync(WorkspaceReference workspace,RepositoryCommand command,CancellationToken ct){if(!Executables.Contains(command.Executable))return Fail("tool_rejected","Executable is not allowed.");var isGit=command.Executable.Equals("git",StringComparison.OrdinalIgnoreCase);if(isGit&&(command.Arguments.Count==0||!GitCommands.Contains(command.Arguments[0])))return Fail("tool_rejected","Git subcommand is not allowed.");if(command.TimeoutSeconds is<1 or>600)return Fail("tool_rejected","Command timeout is outside the allowed range.");var root=workspaces.FromReference(workspace);var cwd=Resolve(root,command.WorkingDirectory??".",true);var result=await processes.RunAsync(command.Executable,isGit?Git(command.Arguments):command.Arguments,cwd,command.TimeoutSeconds,limit,null,ct);return result.TimedOut?Fail("tool_timeout","Command timed out."):new(result.Succeeded,Bound(result.Output,out var truncated),result.Succeeded?null:"command_failed",result.Succeeded?null:"Command exited unsuccessfully.",truncated);}
    private string Resolve(string root,string relative,bool directory){if(Path.IsPathRooted(relative)||relative.Split('/','\\').Contains(".."))throw new ArgumentException("Repository path is invalid.");var path=Path.GetFullPath(Path.Combine(root,relative));if(path!=root&&!path.StartsWith(root+Path.DirectorySeparatorChar,StringComparison.OrdinalIgnoreCase))throw new ArgumentException("Repository path escapes the workspace.");for(var current=path;current.StartsWith(root,StringComparison.OrdinalIgnoreCase);current=Path.GetDirectoryName(current)!){if(File.Exists(current)||Directory.Exists(current)){var attributes=File.GetAttributes(current);if(attributes.HasFlag(FileAttributes.ReparsePoint))throw new ArgumentException("Symbolic-link paths are not permitted.");}if(current==root)break;}if(directory&&!Directory.Exists(path))throw new DirectoryNotFoundException();if(!directory&&!File.Exists(path))throw new FileNotFoundException();return path;}
    private static IReadOnlyList<string> Git(IReadOnlyList<string> arguments)=>["-c","core.longpaths=true",..arguments];private string Bound(string value,out bool truncated){truncated=value.Length>limit;return truncated?value[..limit]:value;} private static bool IsSensitive(string path)=>path.Split('/','\\').Any(x=>x.Equals(".git",StringComparison.OrdinalIgnoreCase)||x.Equals(".env",StringComparison.OrdinalIgnoreCase)||x.Contains("credential",StringComparison.OrdinalIgnoreCase));private static RepositoryToolResult Ok(string output,bool truncated=false)=>new(true,output,null,null,truncated);private static RepositoryToolResult Fail(string code,string message)=>new(false,string.Empty,code,message);
}

public sealed class AllowlistedChildProcessEnvironmentBuilder:IChildProcessEnvironmentBuilder
{
    private static readonly string[] WindowsNames=["SystemRoot","WINDIR","PATH","PATHEXT","COMSPEC","USERPROFILE","HOME","APPDATA","LOCALAPPDATA","TEMP","TMP","ProgramFiles","ProgramFiles(x86)","ProgramW6432","DOTNET_ROOT","NUGET_PACKAGES","NODE_PATH"];
    private static readonly string[] PortableNames=["PATH","HOME","TEMP","TMP","DOTNET_ROOT","NUGET_PACKAGES","NODE_PATH"];
    private static readonly string[] NetworkNames=["HTTP_PROXY","HTTPS_PROXY","NO_PROXY","ALL_PROXY","SSL_CERT_FILE","SSL_CERT_DIR","GIT_SSL_CAINFO"];
    public IReadOnlyDictionary<string,string> Build(){var comparer=OperatingSystem.IsWindows()?StringComparer.OrdinalIgnoreCase:StringComparer.Ordinal;var parent=Environment.GetEnvironmentVariables().Cast<System.Collections.DictionaryEntry>().ToDictionary(x=>(string)x.Key,x=>(string?)x.Value??string.Empty,comparer);var result=new Dictionary<string,string>(comparer);foreach(var name in (OperatingSystem.IsWindows()?WindowsNames:PortableNames).Concat(NetworkNames))if(parent.TryGetValue(name,out var value)&&!string.IsNullOrEmpty(value))result[name]=value;return result;}
}

internal sealed record ProcessResult(bool Succeeded,bool TimedOut,string Output,bool StartFailure=false,int? ExitCode=null);
internal sealed class SafeProcess(IChildProcessEnvironmentBuilder environments,Microsoft.Extensions.Logging.ILogger<SafeProcess> logger)
{
    public async Task<ProcessResult> RunAsync(string executable,IReadOnlyList<string> arguments,string cwd,int timeoutSeconds,int outputLimit,string? standardInput,CancellationToken ct)
    {
        var supplied=environments.Build();logger.LogDebug("Launching sanitized child process on {OperatingSystem}: {Executable}; variables {VariableNames}; working directory reference supplied.",System.Runtime.InteropServices.RuntimeInformation.OSDescription,executable,supplied.Keys.OrderBy(x=>x,StringComparer.OrdinalIgnoreCase));var start=new ProcessStartInfo(executable){WorkingDirectory=cwd,UseShellExecute=false,RedirectStandardOutput=true,RedirectStandardError=true,RedirectStandardInput=standardInput is not null,CreateNoWindow=true};foreach(var argument in arguments)start.ArgumentList.Add(argument);start.Environment.Clear();foreach(var item in supplied)start.Environment[item.Key]=item.Value;using var process=new Process{StartInfo=start};var output=new StringBuilder();process.OutputDataReceived+=(_,e)=>Append(e.Data);process.ErrorDataReceived+=(_,e)=>Append(e.Data);try{process.Start();}catch(Exception ex) when(ex is System.ComponentModel.Win32Exception or InvalidOperationException){logger.LogWarning("Sanitized child process failed to start on {OperatingSystem}: {Executable}.",System.Runtime.InteropServices.RuntimeInformation.OSDescription,executable);return new(false,false,"Process could not be started.",true);}process.BeginOutputReadLine();process.BeginErrorReadLine();if(standardInput is not null){await process.StandardInput.WriteAsync(standardInput.AsMemory(),ct);process.StandardInput.Close();}using var timeout=new CancellationTokenSource(TimeSpan.FromSeconds(timeoutSeconds));using var linked=CancellationTokenSource.CreateLinkedTokenSource(ct,timeout.Token);try{await process.WaitForExitAsync(linked.Token);logger.LogDebug("Sanitized child process exited: {Executable}; exit code {ExitCode}; timeout false.",executable,process.ExitCode);return new(process.ExitCode==0,false,output.ToString(),false,process.ExitCode);}catch(OperationCanceledException) when(timeout.IsCancellationRequested&&!ct.IsCancellationRequested){try{process.Kill(true);}catch{}logger.LogWarning("Sanitized child process timed out: {Executable}; timeout true.",executable);return new(false,true,output.ToString());}void Append(string? line){if(line is null||output.Length>=outputLimit)return;var remaining=outputLimit-output.Length;output.AppendLine(line.Length<=remaining?line:line[..remaining]);}
    }
}

internal sealed class ExecutionEnvironmentReadinessService(IChildProcessEnvironmentBuilder environments,SafeProcess processes,IOptions<ExecutionOptions> options):IExecutionEnvironmentReadinessService
{
 public async Task<ExecutionEnvironmentReadiness> CheckAsync(CancellationToken ct){var supplied=environments.Build();var blockers=new List<string>();var core=!OperatingSystem.IsWindows()||supplied.ContainsKey("SystemRoot");if(!core)blockers.Add("SystemRoot is unavailable in the Windows child-process environment.");var root=Path.GetFullPath(options.Value.WorkspaceRoot??Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"Impersonate","workspaces"));var writable=false;try{Directory.CreateDirectory(root);var probe=Path.Combine(root,$".readiness-{Guid.NewGuid():N}");await File.WriteAllTextAsync(probe,"ready",ct);File.Delete(probe);writable=true;}catch(Exception ex) when(ex is IOException or UnauthorizedAccessException){blockers.Add("The configured workspace root is not writable.");}var git=await processes.RunAsync("git",["--version"],root,15,1000,null,ct);if(git.StartFailure)blockers.Add("Git is not available.");else if(!git.Succeeded)blockers.Add("Git version validation failed.");return new(blockers.Count==0,System.Runtime.InteropServices.RuntimeInformation.OSDescription,!git.StartFailure,git.Succeeded,writable,core,git.Succeeded,supplied.Keys.OrderBy(x=>x,StringComparer.OrdinalIgnoreCase).ToList(),blockers);}
}
