using System.Diagnostics;
using System.Text;
using Impersonate.Application.Execution;
using Microsoft.Extensions.Options;

namespace Impersonate.Infrastructure.Execution;

internal sealed class RepositoryWorkspaceService:IRepositoryWorkspaceService
{
    private const string Prefix="workspace:";private readonly string root;private readonly IExecutionArtifactStore artifacts;private readonly int outputLimit;
    public RepositoryWorkspaceService(IOptions<ExecutionOptions> options,IExecutionArtifactStore artifacts){root=Path.GetFullPath(options.Value.WorkspaceRoot??Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"Impersonate","workspaces"));this.artifacts=artifacts;outputLimit=options.Value.MaximumToolOutputCharacters;Directory.CreateDirectory(root);}
    public async Task<WorkspacePreparationResult> PrepareAsync(WorkspaceRequest request,CancellationToken ct)
    {
        var relative=Path.Combine(request.ProjectId.ToString("N"),request.PipelineRunId.ToString("N"),request.PlannedTaskId.ToString("N"),request.AttemptNumber.ToString());var path=Resolve(relative);
        try
        {
            if(Directory.Exists(path))Directory.Delete(path,true);Directory.CreateDirectory(Path.GetDirectoryName(path)!);
            var clone=await SafeProcess.RunAsync("git",["clone","--no-tags","--single-branch","--branch",request.DefaultBranch,"--",request.RepositoryUrl,path],root,300,outputLimit,null,ct);if(!clone.Succeeded)return new(false,null,"workspace_preparation_failed",Safe(clone.Output));
            foreach(var reference in request.ApprovedPatchReferences.Concat(request.CurrentPatchReference is null?[]:[request.CurrentPatchReference])){var patch=await artifacts.ReadTextAsync(reference,2_000_000,ct);var applied=await SafeProcess.RunAsync("git",["apply","--whitespace=nowarn","-"],path,120,outputLimit,patch,ct);if(!applied.Succeeded)return new(false,null,"workspace_preparation_failed","An approved patch could not be applied to the isolated workspace.");}
            return new(true,new(Prefix+relative.Replace('\\','/')),null,null);
        }
        catch(Exception ex) when(ex is IOException or UnauthorizedAccessException or InvalidOperationException){return new(false,null,"workspace_preparation_failed",Safe(ex.Message));}
    }
    public Task CleanupAsync(WorkspaceReference workspace,CancellationToken ct){ct.ThrowIfCancellationRequested();var path=FromReference(workspace);if(Directory.Exists(path))Directory.Delete(path,true);return Task.CompletedTask;}
    internal string FromReference(WorkspaceReference reference){if(!reference.Value.StartsWith(Prefix,StringComparison.Ordinal))throw new ArgumentException("Workspace reference is invalid.");return Resolve(reference.Value[Prefix.Length..].Replace('/',Path.DirectorySeparatorChar));}
    private string Resolve(string relative){if(Path.IsPathRooted(relative)||relative.Split(Path.DirectorySeparatorChar,Path.AltDirectorySeparatorChar).Contains(".."))throw new ArgumentException("Workspace path is invalid.");var path=Path.GetFullPath(Path.Combine(root,relative));if(!path.StartsWith(root+Path.DirectorySeparatorChar,StringComparison.OrdinalIgnoreCase))throw new ArgumentException("Workspace path escapes the configured root.");return path;}
    private static string Safe(string value)=>value.Length<=1000?value:value[..1000];
}

internal sealed class SafeRepositoryTools(RepositoryWorkspaceService workspaces,IOptions<ExecutionOptions> options):IRepositoryTools
{
    private static readonly HashSet<string> Executables=new(StringComparer.OrdinalIgnoreCase){"dotnet","node","npm","npx","git"};
    private static readonly HashSet<string> GitCommands=new(StringComparer.OrdinalIgnoreCase){"status","diff","apply","rev-parse","ls-files","checkout","clone"};
    private readonly int limit=options.Value.MaximumToolOutputCharacters;
    public Task<RepositoryToolResult> ListFilesAsync(WorkspaceReference workspace,string relativePath,CancellationToken ct){var root=workspaces.FromReference(workspace);var path=Resolve(root,relativePath,true);var files=Directory.EnumerateFiles(path,"*",SearchOption.AllDirectories).Where(x=>!x.Contains($"{Path.DirectorySeparatorChar}.git{Path.DirectorySeparatorChar}")).Take(1000).Select(x=>Path.GetRelativePath(root,x).Replace('\\','/'));return Task.FromResult(Ok(string.Join('\n',files)));}
    public async Task<RepositoryToolResult> ReadFileAsync(WorkspaceReference workspace,string relativePath,CancellationToken ct){var root=workspaces.FromReference(workspace);if(IsSensitive(relativePath))return Fail("tool_rejected","Credential and repository metadata files cannot be read.");var path=Resolve(root,relativePath,false);var info=new FileInfo(path);if(info.Length>1_000_000)return Fail("tool_rejected","File exceeds the read limit.");var bytes=await File.ReadAllBytesAsync(path,ct);if(bytes.AsSpan().IndexOf((byte)0)>=0)return Fail("tool_rejected","Binary files are not supported.");return Ok(Bound(Encoding.UTF8.GetString(bytes),out var truncated),truncated);}
    public async Task<RepositoryToolResult> SearchTextAsync(WorkspaceReference workspace,string query,string relativePath,CancellationToken ct){if(string.IsNullOrWhiteSpace(query))return Fail("tool_rejected","Search query is required.");var root=workspaces.FromReference(workspace);var path=Resolve(root,relativePath,true);var results=new List<string>();foreach(var file in Directory.EnumerateFiles(path,"*",SearchOption.AllDirectories).Where(x=>!x.Contains($"{Path.DirectorySeparatorChar}.git{Path.DirectorySeparatorChar}"))){ct.ThrowIfCancellationRequested();if(new FileInfo(file).Length>1_000_000)continue;string text;try{text=await File.ReadAllTextAsync(file,ct);}catch{continue;}var lines=text.Split('\n');for(var i=0;i<lines.Length&&results.Count<200;i++)if(lines[i].Contains(query,StringComparison.OrdinalIgnoreCase))results.Add($"{Path.GetRelativePath(root,file).Replace('\\','/')}:{i+1}:{lines[i].TrimEnd()}");if(results.Count>=200)break;}return Ok(Bound(string.Join('\n',results),out var truncated),truncated);}
    public async Task<RepositoryToolResult> ApplyPatchAsync(WorkspaceReference workspace,string patch,CancellationToken ct){if(string.IsNullOrWhiteSpace(patch)||patch.IndexOf('\0')>=0)return Fail("tool_rejected","A UTF-8 text patch is required.");if(patch.Contains("GIT binary patch",StringComparison.Ordinal)||patch.Contains("Binary files ",StringComparison.Ordinal))return Fail("tool_rejected","Binary patches are not supported.");if(patch.Contains("../",StringComparison.Ordinal)||patch.Contains("..\\",StringComparison.Ordinal))return Fail("tool_rejected","Patch traversal is not permitted.");var result=await SafeProcess.RunAsync("git",["apply","--whitespace=nowarn","-"],workspaces.FromReference(workspace),120,limit,patch,ct);return result.Succeeded?Ok(result.Output):Fail("tool_rejected",Bound(result.Output,out _));}
    public async Task<RepositoryToolResult> GetDiffAsync(WorkspaceReference workspace,CancellationToken ct){var root=workspaces.FromReference(workspace);var intent=await SafeProcess.RunAsync("git",["add","--intent-to-add","--","."],root,120,limit,null,ct);if(!intent.Succeeded)return Fail("patch_generation_failed",intent.Output);var result=await SafeProcess.RunAsync("git",["diff","--no-ext-diff","--"],root,120,limit,null,ct);if(result.Output.Contains("GIT binary patch",StringComparison.Ordinal)||result.Output.Contains("Binary files ",StringComparison.Ordinal))return Fail("patch_generation_failed","Binary patches are not supported.");return result.Succeeded?Ok(Bound(result.Output,out var truncated),truncated):Fail("patch_generation_failed",result.Output);}
    public async Task<RepositoryToolResult> RunCommandAsync(WorkspaceReference workspace,RepositoryCommand command,CancellationToken ct){if(!Executables.Contains(command.Executable))return Fail("tool_rejected","Executable is not allowed.");if(command.Executable.Equals("git",StringComparison.OrdinalIgnoreCase)&&(command.Arguments.Count==0||!GitCommands.Contains(command.Arguments[0])))return Fail("tool_rejected","Git subcommand is not allowed.");if(command.TimeoutSeconds is<1 or>600)return Fail("tool_rejected","Command timeout is outside the allowed range.");var root=workspaces.FromReference(workspace);var cwd=Resolve(root,command.WorkingDirectory??".",true);var result=await SafeProcess.RunAsync(command.Executable,command.Arguments,cwd,command.TimeoutSeconds,limit,null,ct);return result.TimedOut?Fail("tool_timeout","Command timed out."):new(result.Succeeded,Bound(result.Output,out var truncated),result.Succeeded?null:"command_failed",result.Succeeded?null:"Command exited unsuccessfully.",truncated);}
    private string Resolve(string root,string relative,bool directory){if(Path.IsPathRooted(relative)||relative.Split('/','\\').Contains(".."))throw new ArgumentException("Repository path is invalid.");var path=Path.GetFullPath(Path.Combine(root,relative));if(path!=root&&!path.StartsWith(root+Path.DirectorySeparatorChar,StringComparison.OrdinalIgnoreCase))throw new ArgumentException("Repository path escapes the workspace.");for(var current=path;current.StartsWith(root,StringComparison.OrdinalIgnoreCase);current=Path.GetDirectoryName(current)!){if(File.Exists(current)||Directory.Exists(current)){var attributes=File.GetAttributes(current);if(attributes.HasFlag(FileAttributes.ReparsePoint))throw new ArgumentException("Symbolic-link paths are not permitted.");}if(current==root)break;}if(directory&&!Directory.Exists(path))throw new DirectoryNotFoundException();if(!directory&&!File.Exists(path))throw new FileNotFoundException();return path;}
    private string Bound(string value,out bool truncated){truncated=value.Length>limit;return truncated?value[..limit]:value;} private static bool IsSensitive(string path)=>path.Split('/','\\').Any(x=>x.Equals(".git",StringComparison.OrdinalIgnoreCase)||x.Equals(".env",StringComparison.OrdinalIgnoreCase)||x.Contains("credential",StringComparison.OrdinalIgnoreCase));private static RepositoryToolResult Ok(string output,bool truncated=false)=>new(true,output,null,null,truncated);private static RepositoryToolResult Fail(string code,string message)=>new(false,string.Empty,code,message);
}

internal sealed record ProcessResult(bool Succeeded,bool TimedOut,string Output);
internal static class SafeProcess
{
    public static async Task<ProcessResult> RunAsync(string executable,IReadOnlyList<string> arguments,string cwd,int timeoutSeconds,int outputLimit,string? standardInput,CancellationToken ct)
    {
        var start=new ProcessStartInfo(executable){WorkingDirectory=cwd,UseShellExecute=false,RedirectStandardOutput=true,RedirectStandardError=true,RedirectStandardInput=standardInput is not null,CreateNoWindow=true};foreach(var argument in arguments)start.ArgumentList.Add(argument);start.Environment.Clear();foreach(var key in new[]{"PATH","DOTNET_ROOT","NUGET_PACKAGES","NODE_PATH","TEMP","TMP"})if(Environment.GetEnvironmentVariable(key) is{} value)start.Environment[key]=value;using var process=new Process{StartInfo=start};var output=new StringBuilder();process.OutputDataReceived+=(_,e)=>Append(e.Data);process.ErrorDataReceived+=(_,e)=>Append(e.Data);process.Start();process.BeginOutputReadLine();process.BeginErrorReadLine();if(standardInput is not null){await process.StandardInput.WriteAsync(standardInput.AsMemory(),ct);process.StandardInput.Close();}using var timeout=new CancellationTokenSource(TimeSpan.FromSeconds(timeoutSeconds));using var linked=CancellationTokenSource.CreateLinkedTokenSource(ct,timeout.Token);try{await process.WaitForExitAsync(linked.Token);return new(process.ExitCode==0,false,output.ToString());}catch(OperationCanceledException) when(timeout.IsCancellationRequested&&!ct.IsCancellationRequested){try{process.Kill(true);}catch{}return new(false,true,output.ToString());}void Append(string? line){if(line is null||output.Length>=outputLimit)return;var remaining=outputLimit-output.Length;output.AppendLine(line.Length<=remaining?line:line[..remaining]);}
    }
}
