// <auto-generated />
using System;
using Impersonate.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Impersonate.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ImpersonateDbContext))]
    [Migration("20260723205946_AddExecutionInfrastructureBlocking")]
    partial class AddExecutionInfrastructureBlocking
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Impersonate.Domain.Ai.AiProviderConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastFailureCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset?>("LastModelSyncAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastSafeFailureMessage")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset?>("LastValidatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("ProviderType")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("AiProviderConnections", (string)null);
                });

            modelBuilder.Entity("Impersonate.Domain.Ai.DiscoveredModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CapabilitiesJson")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("CapabilitySource")
                        .HasColumnType("int");

                    b.Property<int?>("ContextWindowSize")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTimeOffset>("DiscoveredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("LastSeenAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("LifecycleStatus")
                        .HasColumnType("int");

                    b.Property<int?>("MaximumOutputSize")
                        .HasColumnType("int");

                    b.Property<Guid>("ProviderConnectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProviderModelId")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("ProviderType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProviderConnectionId", "ProviderModelId")
                        .IsUnique();

                    b.ToTable("DiscoveredModels", (string)null);
                });

            modelBuilder.Entity("Impersonate.Domain.Ai.ModelSelectionDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CandidateSummaryJson")
                        .IsRequired()
                        .HasMaxLength(16000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DiscoveredModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EscalatedFromDecisionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("MetadataVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid?>("PipelineRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PlannedTaskId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("ProviderConnectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<string>("ScoreBreakdownJson")
                        .IsRequired()
                        .HasMaxLength(12000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SelectionSource")
                        .HasColumnType("int");

                    b.Property<Guid?>("TaskAttemptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TaskProfileJson")
                        .IsRequired()
                        .HasMaxLength(12000)
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "PipelineRunId");

                    b.HasIndex("PlannedTaskId", "TaskAttemptId", "Role");

                    b.ToTable("ModelSelectionDecisions", (string)null);
                });

            modelBuilder.Entity("Impersonate.Domain.Ai.ProjectAiRoutingPolicy", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AllowAutomaticEscalation")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowPreviewModels")
                        .HasColumnType("bit");

                    b.Property<string>("AllowedProvidersJson")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("BlockedProvidersJson")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("CostPreference")
                        .HasColumnType("int");

                    b.Property<Guid?>("FixedModelOverrideId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("LatencyPreference")
                        .HasColumnType("int");

                    b.Property<int>("MaximumEscalationCount")
                        .HasColumnType("int");

                    b.Property<bool>("PreferReviewerDiversity")
                        .HasColumnType("bit");

                    b.Property<int?>("PreferredProvider")
                        .HasColumnType("int");

                    b.Property<int>("ReviewerDiversityWeight")
                        .HasColumnType("int");

                    b.HasKey("ProjectId");

                    b.ToTable("ProjectAiRoutingPolicies", (string)null);
                });

            modelBuilder.Entity("Impersonate.Domain.Pipelines.LoopRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("ContinueOnTaskFailure")
                        .HasColumnType("bit");

                    b.Property<string>("CurrentStage")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("FailureReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoopDefinitionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LoopDefinitionVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("MaximumRevisionAttempts")
                        .HasColumnType("int");

                    b.Property<Guid>("PipelineRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("StopReason")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PipelineRunId")
                        .IsUnique();

                    b.ToTable("LoopRuns", (string)null);
                });

            modelBuilder.Entity("Impersonate.Domain.Pipelines.PipelineRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CancelledAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ExecutionClaimExpiresAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("ExecutionClaimId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ExecutionClaimedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("ExecutionClaimedTaskId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ExecutionWorkerId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FailureReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FeatureRequest")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<Guid?>("InfrastructureBlockedTaskId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("InfrastructureFailureCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("InfrastructureFailureMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset?>("PlanningClaimExpiresAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("PlanningClaimId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("PlanningClaimedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PlanningContextArtifactReference")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PlanningContextSummary")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("PlanningFrameworksJson")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("PlanningLanguagesJson")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("PlanningWorkerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("StopReason")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "CreatedAtUtc");

                    b.HasIndex("ProjectId", "Status");

                    b.HasIndex("Status", "ExecutionClaimExpiresAtUtc");

                    b.ToTable("PipelineRuns", (string)null);
                });

            modelBuilder.Entity("Impersonate.Domain.Pipelines.PipelineRunEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("NewState")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("PipelineRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PlannedTaskId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PreviousState")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PipelineRunId", "Sequence")
                        .IsUnique();

                    b.HasIndex("ProjectId", "CreatedAtUtc");

                    b.ToTable("PipelineRunEvents", (string)null);
                });

            modelBuilder.Entity("Impersonate.Domain.Pipelines.PlannedTask", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AcceptanceCriteriaJson")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AffectedAreasJson")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("CoderModelOverrideId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ConflictRisk")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DependsOnTaskIdsJson")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<bool>("EstablishesSharedContract")
                        .HasColumnType("bit");

                    b.Property<string>("ExecutionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("FailureReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaximumRevisionAttempts")
                        .HasColumnType("int");

                    b.Property<bool>("OrderAdjusted")
                        .HasColumnType("bit");

                    b.Property<string>("OrderAdjustmentReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("OriginalPlannerSequence")
                        .HasColumnType("int");

                    b.Property<Guid>("PipelineRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RepositoryEvidenceJson")
                        .IsRequired()
                        .HasMaxLength(16000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ReviewerModelOverrideId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RevisionCount")
                        .HasColumnType("int");

                    b.Property<string>("Risk")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<string>("SkipReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("PipelineRunId", "Sequence")
                        .IsUnique();

                    b.ToTable("PlannedTasks", (string)null);
                });

            modelBuilder.Entity("Impersonate.Domain.Pipelines.PlanningAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FailureMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("InputTokenCount")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("OutputTokenCount")
                        .HasColumnType("int");

                    b.Property<Guid>("PipelineRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PromptVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProviderRequestId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("StartedAtUtc");

                    b.HasIndex("Status");

                    b.HasIndex("PipelineRunId", "AttemptNumber")
                        .IsUnique();

                    b.ToTable("PlanningAttempts", (string)null);
                });

            modelBuilder.Entity("Impersonate.Domain.Pipelines.ReviewDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Feedback")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("FindingsJson")
                        .IsRequired()
                        .HasMaxLength(16000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InputTokenCount")
                        .HasColumnType("int");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<string>("Model")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int?>("OutputTokenCount")
                        .HasColumnType("int");

                    b.Property<Guid>("PlannedTaskId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PromptVersion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Provider")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProviderRequestId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ReviewedPatchSha256")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("TaskAttemptId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TaskAttemptId");

                    b.HasIndex("PlannedTaskId", "CreatedAtUtc");

                    b.HasIndex("PlannedTaskId", "IsCurrent");

                    b.ToTable("ReviewDecisions", (string)null);
                });

            modelBuilder.Entity("Impersonate.Domain.Pipelines.TaskAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("int");

                    b.Property<string>("AttemptType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ChangedFilesJson")
                        .IsRequired()
                        .HasMaxLength(16000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("InputTokenCount")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int?>("OutputTokenCount")
                        .HasColumnType("int");

                    b.Property<string>("PatchArtifactReference")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PatchSha256")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("PlannedTaskId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PromptVersion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Provider")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProviderRequestId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Summary")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("ToolStepCount")
                        .HasColumnType("int");

                    b.Property<string>("ValidationSummaryJson")
                        .IsRequired()
                        .HasMaxLength(16000)
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("PlannedTaskId", "AttemptNumber")
                        .IsUnique();

                    b.ToTable("TaskAttempts", (string)null);
                });

            modelBuilder.Entity("Impersonate.Domain.Projects.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DefaultBranch")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("RepositoryUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("Status");

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("Impersonate.Infrastructure.Ai.ProviderCredentialSecret", b =>
                {
                    b.Property<Guid>("ConnectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProtectedPayload")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ConnectionId");

                    b.ToTable("ProviderCredentialSecrets", (string)null);
                });

            modelBuilder.Entity("Impersonate.Domain.Ai.DiscoveredModel", b =>
                {
                    b.HasOne("Impersonate.Domain.Ai.AiProviderConnection", null)
                        .WithMany("Models")
                        .HasForeignKey("ProviderConnectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Impersonate.Domain.Pipelines.LoopRun", b =>
                {
                    b.HasOne("Impersonate.Domain.Pipelines.PipelineRun", null)
                        .WithOne("LoopRun")
                        .HasForeignKey("Impersonate.Domain.Pipelines.LoopRun", "PipelineRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Impersonate.Domain.Pipelines.PipelineRun", b =>
                {
                    b.HasOne("Impersonate.Domain.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Impersonate.Domain.Pipelines.PipelineRunEvent", b =>
                {
                    b.HasOne("Impersonate.Domain.Pipelines.PipelineRun", null)
                        .WithMany("Events")
                        .HasForeignKey("PipelineRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Impersonate.Domain.Pipelines.PlannedTask", b =>
                {
                    b.HasOne("Impersonate.Domain.Pipelines.PipelineRun", null)
                        .WithMany("Tasks")
                        .HasForeignKey("PipelineRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Impersonate.Domain.Pipelines.PlanningAttempt", b =>
                {
                    b.HasOne("Impersonate.Domain.Pipelines.PipelineRun", null)
                        .WithMany()
                        .HasForeignKey("PipelineRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Impersonate.Domain.Pipelines.ReviewDecision", b =>
                {
                    b.HasOne("Impersonate.Domain.Pipelines.PlannedTask", null)
                        .WithMany("ReviewDecisions")
                        .HasForeignKey("PlannedTaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Impersonate.Domain.Pipelines.TaskAttempt", null)
                        .WithMany()
                        .HasForeignKey("TaskAttemptId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Impersonate.Domain.Pipelines.TaskAttempt", b =>
                {
                    b.HasOne("Impersonate.Domain.Pipelines.PlannedTask", null)
                        .WithMany("Attempts")
                        .HasForeignKey("PlannedTaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Impersonate.Domain.Ai.AiProviderConnection", b =>
                {
                    b.Navigation("Models");
                });

            modelBuilder.Entity("Impersonate.Domain.Pipelines.PipelineRun", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("LoopRun")
                        .IsRequired();

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Impersonate.Domain.Pipelines.PlannedTask", b =>
                {
                    b.Navigation("Attempts");

                    b.Navigation("ReviewDecisions");
                });
#pragma warning restore 612, 618
        }
    }
}
