using Impersonate.Application.Ai;
using Impersonate.Domain.Pipelines;
using Impersonate.Domain.Ai;
namespace Impersonate.Application.Execution;

public sealed record WorkspacePatchReference(Guid TaskId,int Sequence,string ArtifactReference);
public sealed record WorkspaceRequest(Guid ProjectId,Guid PipelineRunId,Guid PlannedTaskId,int AttemptNumber,string RepositoryUrl,string DefaultBranch,IReadOnlyList<WorkspacePatchReference> ApprovedDependencyPatches,string? CurrentPatchReference);
public sealed record WorkspaceReference(string Value);
public sealed record WorkspacePreparationResult(bool Succeeded,WorkspaceReference? Workspace,string? FailureCode,string? FailureMessage,string? SourceBaseCommitSha=null,string? ComposedTreeFingerprint=null,IReadOnlyList<Guid>? DependencyTaskIds=null,bool CurrentRevisionPatchApplied=false,int? FailingDependencySequence=null);
public interface IRepositoryWorkspaceService { Task<WorkspacePreparationResult> PrepareAsync(WorkspaceRequest request,CancellationToken ct); Task CleanupAsync(WorkspaceReference workspace,CancellationToken ct); }
public interface IChildProcessEnvironmentBuilder { IReadOnlyDictionary<string,string> Build(); }
public sealed record ExecutionEnvironmentReadiness(bool Ready,string OperatingSystem,bool GitAvailable,bool GitVersionSucceeded,bool WorkspaceRootWritable,bool CoreEnvironmentValid,bool SanitizedProcessSucceeded,IReadOnlyList<string> SuppliedVariableNames,IReadOnlyList<string> Blockers);
public interface IExecutionEnvironmentReadinessService { Task<ExecutionEnvironmentReadiness> CheckAsync(CancellationToken ct); }
public sealed record ArtifactScope(Guid ProjectId,Guid PipelineRunId,Guid PlannedTaskId,int AttemptNumber);
public sealed record StoredArtifact(string Reference,string Sha256,long ContentLength,string MediaType,DateTimeOffset CreatedAtUtc);
public interface IExecutionArtifactStore { Task<StoredArtifact> WriteTextAsync(ArtifactScope scope,string name,string content,string mediaType,CancellationToken ct); Task<string> ReadTextAsync(string reference,int maximumCharacters,CancellationToken ct); }
public sealed record RepositoryToolResult(bool Succeeded,string Output,string? FailureCode=null,string? FailureMessage=null,bool Truncated=false);
public sealed record RepositoryCommand(string Executable,IReadOnlyList<string> Arguments,string? WorkingDirectory=null,int TimeoutSeconds=120);
public interface IRepositoryTools
{
 Task<RepositoryToolResult> ListFilesAsync(WorkspaceReference workspace,string relativePath,CancellationToken ct); Task<RepositoryToolResult> ReadFileAsync(WorkspaceReference workspace,string relativePath,CancellationToken ct); Task<RepositoryToolResult> SearchTextAsync(WorkspaceReference workspace,string query,string relativePath,CancellationToken ct); Task<RepositoryToolResult> ApplyPatchAsync(WorkspaceReference workspace,string patch,CancellationToken ct); Task<RepositoryToolResult> GetDiffAsync(WorkspaceReference workspace,CancellationToken ct); Task<RepositoryToolResult> RunCommandAsync(WorkspaceReference workspace,RepositoryCommand command,CancellationToken ct);
}
public sealed record RepositoryEvidenceExcerpt(string Path,string Content,bool Truncated);
public sealed record CoderContext(Guid ProjectId,Guid PipelineRunId,string FeatureRequest,Guid PlannedTaskId,string TaskTitle,string TaskDescription,IReadOnlyList<string> AcceptanceCriteria,int AttemptNumber,int RevisionNumber,string? ReviewerFeedback,IReadOnlyList<string> EarlierApprovedSummaries,WorkspaceReference Workspace,SelectedModel Model,string PromptVersion="coder-v1",IReadOnlyList<string>? RepositoryEvidence=null,string? PriorProtocolSummary=null);
public sealed record CoderResult(bool Succeeded,string Summary,IReadOnlyList<string> ChangedFiles,IReadOnlyList<string> ValidationNotes,int ToolStepCount,string? ProviderRequestId,int? InputTokenCount,int? OutputTokenCount,string? FailureCode=null,string? FailureMessage=null,string? ResponseType=null,int SuccessfulReadCount=0,int SuccessfulSearchCount=0,int SuccessfulPatchCount=0,bool RepositoryInspected=false,bool CurrentDiffExists=false,int PrematureCompletionCount=0,int ProviderRoundTripCount=0,int ConsecutiveReadOnlyRounds=0,int MaximumSingleRequestInput=0,string? ProviderResponseStatus=null,string? ProviderIncompleteReason=null,int StructuredOutputRepairCount=0,int NoProgressCorrectionCount=0,int PaidProviderRequestCount=0);
public interface ICoderAgent { Task<CoderResult> ExecuteAsync(CoderContext context,CancellationToken ct); }
public interface IExecutionInvocationStore { Task<Guid?> FindLatestSelectionDecisionIdAsync(Guid taskAttemptId,AgentRole role,CancellationToken ct); Task AddAsync(ExecutionInvocation invocation,CancellationToken ct); Task<IReadOnlyList<ExecutionInvocation>> ListAsync(IReadOnlyCollection<Guid> taskAttemptIds,CancellationToken ct); Task SaveChangesAsync(CancellationToken ct); }
public sealed record ReviewFinding(string Severity,string Message,string? Path=null,int? Line=null);
public sealed record ReviewerContext(Guid ProjectId,Guid PipelineRunId,string FeatureRequest,Guid PlannedTaskId,string TaskTitle,string TaskDescription,IReadOnlyList<string> AcceptanceCriteria,int AttemptNumber,string Patch,string PatchSha256,IReadOnlyList<string> ChangedFiles,IReadOnlyList<string> ValidationResults,string CoderSummary,string? PriorFeedback,WorkspaceReference Workspace,SelectedModel Model,string PromptVersion="reviewer-v1");
public sealed record ReviewerResult(bool Succeeded,ReviewDecisionType? Decision,string Summary,string? Feedback,IReadOnlyList<ReviewFinding> Findings,string? ProviderRequestId,int? InputTokenCount,int? OutputTokenCount,string? FailureCode=null,string? FailureMessage=null);
public interface IReviewerAgent { Task<ReviewerResult> ReviewAsync(ReviewerContext context,CancellationToken ct); }
public sealed class ExecutionOptions { public string? WorkspaceRoot{get;set;} public string? ArtifactRoot{get;set;} public int MaximumArtifactBytes{get;set;}=2_000_000; public int MaximumToolOutputCharacters{get;set;}=100_000; public int MaximumCoderSteps{get;set;}=20; public int MaximumCoderProviderRounds{get;set;}=6; public int MaximumConsecutiveReadOnlyRounds{get;set;}=3; public int MaximumCoderRoundsBeforePatch{get;set;}=4; public int MaximumStructuredOutputRepairAttempts{get;set;}=1; public int MaximumModelFallbacks{get;set;}=2; public int MaximumModelInputTokens{get;set;}=24_000; public int MaximumPaidInvocationsPerTaskAttempt{get;set;}=4; public int MaximumCumulativeInputTokensPerTaskAttempt{get;set;}=60_000; public int MaximumCumulativeOutputTokensPerTaskAttempt{get;set;}=16_000; public int MaximumCoderTaskInputTokens{get;set;}=80_000; public int MaximumCoderTaskOutputTokens{get;set;}=20_000; public int MaximumCoderPaidRequestsPerTask{get;set;}=10; public int MaximumReviewerTaskInputTokens{get;set;}=40_000; public int MaximumReviewerTaskOutputTokens{get;set;}=10_000; public int MaximumReviewerPaidRequestsPerTask{get;set;}=6; public int MaximumSameModelRateLimitRetries{get;set;}=2; public int MaximumAutomaticRateLimitWaitSeconds{get;set;}=15; public int MaximumTotalRateLimitWaitSecondsPerOperation{get;set;}=30; public int InitialRateLimitBackoffMilliseconds{get;set;}=1000; public int MaximumRateLimitBackoffSeconds{get;set;}=8; public int RateLimitJitterMaximumMilliseconds{get;set;}=250; public int CommandTimeoutSeconds{get;set;}=120; public int ClaimMinutes{get;set;}=15; public int MaximumWorkspacePreparationAttempts{get;set;}=3; }
