using Impersonate.Application.Projects;
using Impersonate.Domain.Pipelines;
using Impersonate.Domain.Projects;
using Microsoft.Extensions.Options;

namespace Impersonate.Application.Pipelines;
internal sealed class FeatureDeliveryLoopRegistry(IOptions<PipelineOptions> options):ILoopDefinitionRegistry { public LoopDefinition Get(string id,string? version=null) { if(id!="feature-delivery" || version is not null and not "1") throw new KeyNotFoundException("Loop definition was not found."); var o=options.Value; return new(id,"Feature Delivery","1",Enum.GetValues<LoopStage>(),o.MaximumRevisionAttempts,o.ContinueOnTaskFailure); } }
internal sealed class PipelineRunService(IProjectRepository projects,IPipelineRunRepository runs,ILoopDefinitionRegistry registry):IPipelineRunService
{
 public async Task<PipelineOperationResult<PipelineRunDto>> CreateAsync(Guid projectId,CreatePipelineRunRequest request,CancellationToken ct){var p=await projects.GetAsync(projectId,ct);if(p is null)return PipelineOperationResult<PipelineRunDto>.Fail("not_found","Project was not found.");if(p.Status==ProjectStatus.Off)return PipelineOperationResult<PipelineRunDto>.Fail("project_off","Off projects cannot create pipeline runs.");try{var d=registry.Get("feature-delivery");var run=PipelineRun.Create(projectId,request.FeatureRequest,d.MaximumRevisionAttempts,d.ContinueOnTaskFailure);await runs.AddAsync(run,ct);await runs.SaveChangesAsync(ct);return PipelineOperationResult<PipelineRunDto>.Ok(Map(run));}catch(ArgumentException ex){return PipelineOperationResult<PipelineRunDto>.Fail("validation",ex.Message);}}
 public async Task<PipelineRunDto?> GetAsync(Guid projectId,Guid runId,CancellationToken ct)=>(await runs.GetAsync(projectId,runId,ct)) is{} r?Map(r):null;
 public async Task<IReadOnlyList<PipelineRunDto>> ListAsync(Guid projectId,PipelineRunStatus? status,DateTimeOffset? from,DateTimeOffset? to,CancellationToken ct)=>(await runs.ListAsync(projectId,status,from,to,ct)).Select(Map).ToList();
 public async Task<IReadOnlyList<PipelineEventDto>?> TimelineAsync(Guid projectId,Guid runId,CancellationToken ct)=>(await runs.GetAsync(projectId,runId,ct)) is{} r?r.Events.Select(Map).ToList():null;
 public async Task<PipelineOperationResult<PipelineRunDto>> CancelAsync(Guid projectId,Guid runId,CancellationToken ct){var r=await runs.GetAsync(projectId,runId,ct);if(r is null)return PipelineOperationResult<PipelineRunDto>.Fail("not_found","Pipeline run was not found.");try{r.Cancel();await runs.SaveChangesAsync(ct);return PipelineOperationResult<PipelineRunDto>.Ok(Map(r));}catch(InvalidOperationException ex){return PipelineOperationResult<PipelineRunDto>.Fail("invalid_transition",ex.Message);}}
 private static PipelineRunDto Map(PipelineRun r)=>new(r.Id,r.ProjectId,r.FeatureRequest,r.Status,r.CreatedAtUtc,r.StartedAtUtc,r.CompletedAtUtc,r.CancelledAtUtc,r.FailureReason,r.StopReason,new(r.LoopRun.Id,r.LoopRun.LoopDefinitionId,r.LoopRun.LoopDefinitionVersion,r.LoopRun.Status,r.LoopRun.CurrentStage,r.LoopRun.MaximumRevisionAttempts,r.LoopRun.ContinueOnTaskFailure,r.LoopRun.RetryCount,r.LoopRun.StartedAtUtc,r.LoopRun.CompletedAtUtc,r.LoopRun.StopReason,r.LoopRun.FailureReason),r.Tasks.Select(t=>new PlannedTaskDto(t.Id,t.Sequence,t.Title,t.Description,t.Status,t.RevisionCount,t.MaximumRevisionAttempts,t.Attempts.Count,t.ReviewDecisions.LastOrDefault(x=>x.IsCurrent)?.Decision,t.SkipReason,t.FailureReason)).ToList());
 private static PipelineEventDto Map(PipelineRunEvent e)=>new(e.Id,e.PlannedTaskId,e.EventType,e.PreviousState,e.NewState,e.Message,e.CreatedAtUtc,e.Sequence);
}
