using Impersonate.Domain.Pipelines;
using Impersonate.Domain.Projects;
using Impersonate.Application.Ai;

namespace Impersonate.Application.Pipelines;

public sealed record CreatePipelineRunRequest(string FeatureRequest);
public sealed record PipelineOptions { public int MaximumRevisionAttempts { get; init; } = 3; public bool ContinueOnTaskFailure { get; init; } = true; }
public sealed record LoopRunDto(Guid Id,string LoopDefinitionId,string LoopDefinitionVersion,LoopRunStatus Status,LoopStage CurrentStage,int MaximumRevisionAttempts,bool ContinueOnTaskFailure,int RetryCount,DateTimeOffset? StartedAtUtc,DateTimeOffset? CompletedAtUtc,string? StopReason,string? FailureReason);
public sealed record TaskAttemptDto(Guid Id,int AttemptNumber,TaskAttemptType AttemptType,TaskAttemptStatus Status,string? Provider,string? Model,string? PromptVersion,int? InputTokenCount,int? OutputTokenCount,int ToolStepCount,string? Summary,string? FailureCode,string? FailureReason,IReadOnlyList<string> ChangedFiles,string? PatchArtifactReference,string? PatchSha256,IReadOnlyList<string> ValidationSummary,DateTimeOffset StartedAtUtc,DateTimeOffset? CompletedAtUtc);
public sealed record ReviewDecisionDto(Guid Id,Guid TaskAttemptId,ReviewDecisionType Decision,string? Provider,string? Model,string? PromptVersion,int? InputTokenCount,int? OutputTokenCount,string? ReviewedPatchSha256,string Summary,string? Feedback,string FindingsJson,bool IsCurrent,DateTimeOffset CreatedAtUtc);
public sealed record PlannedTaskDto(Guid Id,int Sequence,string Title,string Description,IReadOnlyList<string> AcceptanceCriteria,PlannedTaskStatus Status,int RevisionCount,int MaximumRevisionAttempts,Guid? CoderModelOverrideId,Guid? ReviewerModelOverrideId,IReadOnlyList<TaskAttemptDto> Attempts,IReadOnlyList<ReviewDecisionDto> Reviews,string? SkipReason,string? FailureReason,IReadOnlyList<Guid> DependsOnTaskIds,IReadOnlyList<string> AffectedAreas,string ChangeType,string Risk,string ConflictRisk,string? ExecutionReason,IReadOnlyList<string> RepositoryEvidence,int OriginalPlannerSequence,bool OrderAdjusted,string? OrderAdjustmentReason,bool EstablishesSharedContract);
public sealed record PlanningAttemptDto(int AttemptNumber,string Provider,string Model,string PromptVersion,PlanningAttemptStatus Status,DateTimeOffset StartedAtUtc,DateTimeOffset? CompletedAtUtc,string? FailureCode,string? FailureMessage,int? InputTokenCount,int? OutputTokenCount);
public sealed record PipelineRunDto(Guid Id,Guid ProjectId,string FeatureRequest,PipelineRunStatus Status,DateTimeOffset CreatedAtUtc,DateTimeOffset? StartedAtUtc,DateTimeOffset? CompletedAtUtc,DateTimeOffset? CancelledAtUtc,string? FailureReason,string? StopReason,LoopRunDto Loop,IReadOnlyList<PlannedTaskDto> Tasks,IReadOnlyList<PlanningAttemptDto> PlanningAttempts,string? InfrastructureFailureCode=null,string? InfrastructureFailureMessage=null,Guid? InfrastructureBlockedTaskId=null,IReadOnlyList<string>? PlanningWarnings=null);
public sealed record PipelineEventDto(Guid Id,Guid? PlannedTaskId,string EventType,string? PreviousState,string NewState,string Message,DateTimeOffset CreatedAtUtc,int Sequence);
public sealed record ModelPreviewDto(bool Ready,Guid? ModelId,string? Provider,string? Model,string? SelectionSource,string? Explanation,string? Blocker,int TotalScore=0,IReadOnlyList<ScoreComponent>? ScoreBreakdown=null,string? MetadataVersion=null,TaskProfile? Profile=null,IReadOnlyList<SelectedModel>? Alternatives=null);
public sealed record TaskRoutingPreviewDto(Guid TaskId,int Sequence,ModelPreviewDto Coder,ModelPreviewDto Reviewer);
public sealed record ExecutionReadinessDto(bool Ready,ModelPreviewDto Coder,ModelPreviewDto Reviewer,IReadOnlyList<string> Blockers,IReadOnlyList<TaskRoutingPreviewDto>? Tasks=null,int DistinctCoderModels=0,int DistinctReviewerModels=0,int TasksUsingOverrides=0);
public sealed record PipelineIntelligenceDto(Guid PipelineRunId,string? RepositoryContextSummary,IReadOnlyList<string> Languages,IReadOnlyList<string> Frameworks,IReadOnlyList<PlannedTaskDto> DependencyGraph,ExecutionReadinessDto Routing,string ActiveStage,Guid? ActiveTaskId,bool PreferReviewerDiversity,int ReviewerDiversityWeight,string HistoricalOutcomeMessage);
public sealed record TaskModelOverridesRequest(Guid? CoderModelId,Guid? ReviewerModelId);
public sealed record PipelineOperationResult<T>(T? Value,string? Error,string? Code) { public bool Succeeded => Error is null; public static PipelineOperationResult<T> Ok(T value)=>new(value,null,null); public static PipelineOperationResult<T> Fail(string code,string error)=>new(default,error,code); }
public interface IPipelineRunRepository { Task AddAsync(PipelineRun run,CancellationToken ct); Task<PipelineRun?> GetAsync(Guid projectId,Guid runId,CancellationToken ct); Task<PipelineRun?> ClaimNextExecutionAsync(Guid claimId,string workerId,DateTimeOffset claimedAt,DateTimeOffset expiresAt,CancellationToken ct); Task<IReadOnlyList<PlanningAttempt>> GetPlanningAttemptsAsync(Guid runId,CancellationToken ct); Task<IReadOnlyList<PipelineRun>> ListAsync(Guid projectId,PipelineRunStatus? status,DateTimeOffset? from,DateTimeOffset? to,CancellationToken ct); Task DeleteAsync(Guid projectId,Guid runId,CancellationToken ct); Task SaveChangesAsync(CancellationToken ct); }
public interface IPipelineRunService { Task<PipelineOperationResult<PipelineRunDto>> CreateAsync(Guid projectId,CreatePipelineRunRequest request,CancellationToken ct); Task<PipelineRunDto?> GetAsync(Guid projectId,Guid runId,CancellationToken ct); Task<IReadOnlyList<PipelineRunDto>> ListAsync(Guid projectId,PipelineRunStatus? status,DateTimeOffset? from,DateTimeOffset? to,CancellationToken ct); Task<IReadOnlyList<PipelineEventDto>?> TimelineAsync(Guid projectId,Guid runId,CancellationToken ct); Task<PipelineOperationResult<PipelineRunDto>> StartPlanningAsync(Guid projectId,Guid runId,CancellationToken ct); Task<PipelineOperationResult<ExecutionReadinessDto>> ExecutionReadinessAsync(Guid projectId,Guid runId,CancellationToken ct); Task<PipelineOperationResult<PipelineIntelligenceDto>> IntelligenceAsync(Guid projectId,Guid runId,CancellationToken ct); Task<PipelineOperationResult<PipelineRunDto>> StartExecutionAsync(Guid projectId,Guid runId,CancellationToken ct); Task<PipelineOperationResult<PipelineRunDto>> RetryExecutionAsync(Guid projectId,Guid runId,CancellationToken ct); Task<PipelineOperationResult<PipelineRunDto>> SetTaskModelOverridesAsync(Guid projectId,Guid runId,Guid taskId,TaskModelOverridesRequest request,CancellationToken ct); Task<PipelineOperationResult<PipelineRunDto>> CancelAsync(Guid projectId,Guid runId,CancellationToken ct); Task<PipelineOperationResult<bool>> DeleteAsync(Guid projectId,Guid runId,CancellationToken ct); }
public sealed record LoopDefinition(string Id,string Name,string Version,IReadOnlyList<LoopStage> Stages,int MaximumRevisionAttempts,bool ContinueOnTaskFailure);
public interface ILoopDefinitionRegistry { LoopDefinition Get(string id,string? version=null); }
