using Impersonate.Application.Projects;
using Impersonate.Domain.Pipelines;
using Impersonate.Domain.Projects;
using Microsoft.Extensions.Options;
using Impersonate.Application.Ai;
using Impersonate.Application.Planning;
using Impersonate.Domain.Ai;
using System.Text.Json;

namespace Impersonate.Application.Pipelines;
internal sealed class FeatureDeliveryLoopRegistry(IOptions<PipelineOptions> options):ILoopDefinitionRegistry { public LoopDefinition Get(string id,string? version=null) { if(id!="feature-delivery" || version is not null and not "1") throw new KeyNotFoundException("Loop definition was not found."); var o=options.Value; return new(id,"Feature Delivery","1",Enum.GetValues<LoopStage>(),o.MaximumRevisionAttempts,o.ContinueOnTaskFailure); } }
internal sealed class PipelineRunService(IProjectRepository projects,IPipelineRunRepository runs,ILoopDefinitionRegistry registry,IModelRouter router,IAiRoutingRepository ai,IOptions<PlannerOptions> planner):IPipelineRunService
{
 public async Task<PipelineOperationResult<PipelineRunDto>> CreateAsync(Guid projectId,CreatePipelineRunRequest request,CancellationToken ct){var p=await projects.GetAsync(projectId,ct);if(p is null)return PipelineOperationResult<PipelineRunDto>.Fail("not_found","Project was not found.");if(p.Status==ProjectStatus.Off)return PipelineOperationResult<PipelineRunDto>.Fail("project_off","Off projects cannot create pipeline runs.");try{var d=registry.Get("feature-delivery");var run=PipelineRun.Create(projectId,request.FeatureRequest,d.MaximumRevisionAttempts,d.ContinueOnTaskFailure);await runs.AddAsync(run,ct);await runs.SaveChangesAsync(ct);return PipelineOperationResult<PipelineRunDto>.Ok(Map(run));}catch(ArgumentException ex){return PipelineOperationResult<PipelineRunDto>.Fail("validation",ex.Message);}}
 public async Task<PipelineRunDto?> GetAsync(Guid projectId,Guid runId,CancellationToken ct)=>(await runs.GetAsync(projectId,runId,ct)) is{} r?Map(r,await runs.GetPlanningAttemptsAsync(runId,ct)):null;
 public async Task<IReadOnlyList<PipelineRunDto>> ListAsync(Guid projectId,PipelineRunStatus? status,DateTimeOffset? from,DateTimeOffset? to,CancellationToken ct)=>(await runs.ListAsync(projectId,status,from,to,ct)).Select(r=>Map(r)).ToList();
 public async Task<IReadOnlyList<PipelineEventDto>?> TimelineAsync(Guid projectId,Guid runId,CancellationToken ct)=>(await runs.GetAsync(projectId,runId,ct)) is{} r?r.Events.Select(Map).ToList():null;
 public async Task<PipelineOperationResult<PipelineRunDto>> StartPlanningAsync(Guid projectId,Guid runId,CancellationToken ct){var p=await projects.GetAsync(projectId,ct);if(p is null)return PipelineOperationResult<PipelineRunDto>.Fail("not_found","Project was not found.");if(p.Status==ProjectStatus.Off)return PipelineOperationResult<PipelineRunDto>.Fail("project_off","Off projects cannot start planning.");var r=await runs.GetAsync(projectId,runId,ct);if(r is null)return PipelineOperationResult<PipelineRunDto>.Fail("not_found","Pipeline run was not found.");try{var selected=await router.SelectAsync(new(projectId,runId,AgentRole.Planner,r.FeatureRequest,FeatureRequest:r.FeatureRequest),ct);ModelSelectionDecision decision;if(selected.Succeeded&&selected.Selection is{} choice)decision=ModelSelectionDecision.Create(projectId,runId,AgentRole.Planner,choice.ConnectionId,choice.DiscoveredModelId,choice.ProviderType.ToString(),choice.ProviderModelId,choice.Source,choice.Score,JsonSerializer.Serialize(selected.Profile),choice.Explanation,JsonSerializer.Serialize(selected.EligibleAlternatives.Take(3)),scoreBreakdown:JsonSerializer.Serialize(choice.ScoreBreakdown??[]),metadataVersion:choice.MetadataVersion);else if(!string.IsNullOrWhiteSpace(planner.Value.Model))decision=ModelSelectionDecision.Create(projectId,runId,AgentRole.Planner,null,null,planner.Value.Provider,planner.Value.Model,ModelSelectionSource.EnvironmentFallback,0,JsonSerializer.Serialize(selected.Profile),"Using legacy environment configuration because automatic routing is unavailable.","[]");else return PipelineOperationResult<PipelineRunDto>.Fail(selected.FailureCode??"no_eligible_model",selected.FailureMessage??"No eligible Planner model is available.");await ai.AddDecisionAsync(decision,ct);r.StartPlanning();await runs.SaveChangesAsync(ct);return PipelineOperationResult<PipelineRunDto>.Ok(Map(r));}catch(InvalidOperationException ex){return PipelineOperationResult<PipelineRunDto>.Fail("invalid_transition",ex.Message);}}
 public async Task<PipelineOperationResult<ExecutionReadinessDto>> ExecutionReadinessAsync(Guid projectId,Guid runId,CancellationToken ct){var project=await projects.GetAsync(projectId,ct);if(project is null)return PipelineOperationResult<ExecutionReadinessDto>.Fail("not_found","Project was not found.");var run=await runs.GetAsync(projectId,runId,ct);if(run is null)return PipelineOperationResult<ExecutionReadinessDto>.Fail("not_found","Pipeline run was not found.");var pending=run.Tasks.Where(x=>x.Status==PlannedTaskStatus.Pending).OrderBy(x=>x.Sequence).ToList();if(pending.Count==0)return PipelineOperationResult<ExecutionReadinessDto>.Fail("invalid_transition","No pending task is available.");var previews=new List<TaskRoutingPreviewDto>();var blockers=new List<string>();foreach(var task in pending){var coder=await Preview(projectId,run,task,AgentRole.Coder,task.CoderModelOverrideId,null,ct);var reviewer=await Preview(projectId,run,task,AgentRole.Reviewer,task.ReviewerModelOverrideId,coder,ct);previews.Add(new(task.Id,task.Sequence,coder,reviewer));if(!coder.Ready)blockers.Add($"Task {task.Sequence} Coder: {coder.Blocker}");if(!reviewer.Ready)blockers.Add($"Task {task.Sequence} Reviewer: {reviewer.Blocker}");}if(project.Status==ProjectStatus.Off)blockers.Add("Off projects cannot start execution.");if(run.Status!=PipelineRunStatus.ReadyForExecution)blockers.Add("Execution can start only from ReadyForExecution.");var first=previews[0];return PipelineOperationResult<ExecutionReadinessDto>.Ok(new(blockers.Count==0,first.Coder,first.Reviewer,blockers,previews,previews.Select(x=>x.Coder.ModelId).Distinct().Count(),previews.Select(x=>x.Reviewer.ModelId).Distinct().Count(),pending.Count(x=>x.CoderModelOverrideId is not null||x.ReviewerModelOverrideId is not null)));}
 public async Task<PipelineOperationResult<PipelineIntelligenceDto>> IntelligenceAsync(Guid projectId,Guid runId,CancellationToken ct){var run=await runs.GetAsync(projectId,runId,ct);if(run is null)return PipelineOperationResult<PipelineIntelligenceDto>.Fail("not_found","Pipeline run was not found.");var routing=await BuildRoutingProjectionAsync(projectId,run,ct);var policy=await ai.GetPolicyAsync(projectId,ct)??ProjectAiRoutingPolicy.Create(projectId);return PipelineOperationResult<PipelineIntelligenceDto>.Ok(new(run.Id,run.PlanningContextSummary,Deserialize(run.PlanningLanguagesJson),Deserialize(run.PlanningFrameworksJson),Map(run).Tasks,routing,run.LoopRun.CurrentStage.ToString(),run.ExecutionClaimedTaskId,policy.PreferReviewerDiversity,policy.ReviewerDiversityWeight,"Historical performance was not used because insufficient samples exist (minimum 10)."));}
 public async Task<PipelineOperationResult<PipelineRunDto>> StartExecutionAsync(Guid projectId,Guid runId,CancellationToken ct){var readiness=await ExecutionReadinessAsync(projectId,runId,ct);if(!readiness.Succeeded)return PipelineOperationResult<PipelineRunDto>.Fail(readiness.Code!,readiness.Error!);if(!readiness.Value!.Ready)return PipelineOperationResult<PipelineRunDto>.Fail("execution_not_ready",string.Join(" ",readiness.Value.Blockers));var run=await runs.GetAsync(projectId,runId,ct);try{run!.StartExecution();await runs.SaveChangesAsync(ct);return PipelineOperationResult<PipelineRunDto>.Ok(Map(run));}catch(InvalidOperationException ex){return PipelineOperationResult<PipelineRunDto>.Fail("conflict",ex.Message);}}
 public async Task<PipelineOperationResult<PipelineRunDto>> RetryExecutionAsync(Guid projectId,Guid runId,CancellationToken ct){var run=await runs.GetAsync(projectId,runId,ct);if(run is null)return PipelineOperationResult<PipelineRunDto>.Fail("not_found","Pipeline run was not found.");try{run.RetryInfrastructure();await runs.SaveChangesAsync(ct);return PipelineOperationResult<PipelineRunDto>.Ok(Map(run));}catch(InvalidOperationException ex){return PipelineOperationResult<PipelineRunDto>.Fail("conflict",ex.Message);}}
 public async Task<PipelineOperationResult<PipelineRunDto>> SetTaskModelOverridesAsync(Guid projectId,Guid runId,Guid taskId,TaskModelOverridesRequest request,CancellationToken ct){var run=await runs.GetAsync(projectId,runId,ct);if(run is null)return PipelineOperationResult<PipelineRunDto>.Fail("not_found","Pipeline run was not found.");var task=run.Tasks.SingleOrDefault(x=>x.Id==taskId);if(task is null)return PipelineOperationResult<PipelineRunDto>.Fail("not_found","Task was not found.");if(request.CoderModelId is{} coder){var check=await router.SelectAsync(new(projectId,runId,AgentRole.Coder,task.Description,coder),ct);if(!check.Succeeded)return PipelineOperationResult<PipelineRunDto>.Fail("invalid_coder_override",check.FailureMessage??"Coder override is invalid.");}if(request.ReviewerModelId is{} reviewer){var check=await router.SelectAsync(new(projectId,runId,AgentRole.Reviewer,task.Description,reviewer),ct);if(!check.Succeeded)return PipelineOperationResult<PipelineRunDto>.Fail("invalid_reviewer_override",check.FailureMessage??"Reviewer override is invalid.");}try{task.SetModelOverrides(request.CoderModelId,request.ReviewerModelId);await runs.SaveChangesAsync(ct);return PipelineOperationResult<PipelineRunDto>.Ok(Map(run));}catch(InvalidOperationException ex){return PipelineOperationResult<PipelineRunDto>.Fail("conflict",ex.Message);}}
 public async Task<PipelineOperationResult<PipelineRunDto>> CancelAsync(Guid projectId,Guid runId,CancellationToken ct){var r=await runs.GetAsync(projectId,runId,ct);if(r is null)return PipelineOperationResult<PipelineRunDto>.Fail("not_found","Pipeline run was not found.");try{r.Cancel();await runs.SaveChangesAsync(ct);return PipelineOperationResult<PipelineRunDto>.Ok(Map(r));}catch(InvalidOperationException ex){return PipelineOperationResult<PipelineRunDto>.Fail("invalid_transition",ex.Message);}}
 private async Task<ExecutionReadinessDto> BuildRoutingProjectionAsync(Guid projectId,PipelineRun run,CancellationToken ct){var previews=new List<TaskRoutingPreviewDto>();var blockers=new List<string>();foreach(var task in run.Tasks.OrderBy(x=>x.Sequence)){var coder=await Preview(projectId,run,task,AgentRole.Coder,task.CoderModelOverrideId,null,ct);var reviewer=await Preview(projectId,run,task,AgentRole.Reviewer,task.ReviewerModelOverrideId,coder,ct);previews.Add(new(task.Id,task.Sequence,coder,reviewer));if(!coder.Ready)blockers.Add($"Task {task.Sequence} Coder: {coder.Blocker}");if(!reviewer.Ready)blockers.Add($"Task {task.Sequence} Reviewer: {reviewer.Blocker}");}var unavailable=new ModelPreviewDto(false,null,null,null,null,null,"No planned task is available.");var first=previews.FirstOrDefault();return new(blockers.Count==0&&previews.Count>0,first?.Coder??unavailable,first?.Reviewer??unavailable,blockers,previews,previews.Where(x=>x.Coder.ModelId is not null).Select(x=>x.Coder.ModelId).Distinct().Count(),previews.Where(x=>x.Reviewer.ModelId is not null).Select(x=>x.Reviewer.ModelId).Distinct().Count(),run.Tasks.Count(x=>x.CoderModelOverrideId is not null||x.ReviewerModelOverrideId is not null));}
 private async Task<ModelPreviewDto> Preview(Guid projectId,PipelineRun run,PlannedTask task,AgentRole role,Guid? overrideId,ModelPreviewDto? coder,CancellationToken ct){var result=await router.SelectAsync(new(projectId,run.Id,role,task.Description,overrideId,TaskTitle:task.Title,AcceptanceCriteria:task.AcceptanceCriteria,FeatureRequest:run.FeatureRequest,RepositoryLanguages:Deserialize(run.PlanningLanguagesJson),RepositoryFrameworks:Deserialize(run.PlanningFrameworksJson),ChangeType:task.ChangeType,AffectedAreas:Deserialize(task.AffectedAreasJson),Risk:task.Risk,ConflictRisk:task.ConflictRisk,RevisionCount:task.RevisionCount,CoderModelId:coder?.ModelId,CoderProvider:coder?.Provider is{} provider&&Enum.TryParse<ProviderType>(provider,out var parsed)?parsed:null),ct);return result.Succeeded&&result.Selection is{} choice?new(true,choice.DiscoveredModelId,choice.ProviderType.ToString(),choice.ProviderModelId,choice.Source.ToString(),choice.Explanation,null,choice.Score,choice.ScoreBreakdown,choice.MetadataVersion,result.Profile,result.EligibleAlternatives.Take(3).ToList()):new(false,null,null,null,null,null,result.FailureMessage,Profile:result.Profile,Alternatives:result.EligibleAlternatives.Take(3).ToList());}
 private static PipelineRunDto Map(PipelineRun r,IReadOnlyList<PlanningAttempt>? attempts=null)=>new(r.Id,r.ProjectId,r.FeatureRequest,r.Status,r.CreatedAtUtc,r.StartedAtUtc,r.CompletedAtUtc,r.CancelledAtUtc,r.FailureReason,r.StopReason,new(r.LoopRun.Id,r.LoopRun.LoopDefinitionId,r.LoopRun.LoopDefinitionVersion,r.LoopRun.Status,r.LoopRun.CurrentStage,r.LoopRun.MaximumRevisionAttempts,r.LoopRun.ContinueOnTaskFailure,r.LoopRun.RetryCount,r.LoopRun.StartedAtUtc,r.LoopRun.CompletedAtUtc,r.LoopRun.StopReason,r.LoopRun.FailureReason),r.Tasks.Select(t=>new PlannedTaskDto(t.Id,t.Sequence,t.Title,t.Description,t.AcceptanceCriteria,t.Status,t.RevisionCount,t.MaximumRevisionAttempts,t.CoderModelOverrideId,t.ReviewerModelOverrideId,t.Attempts.Select(a=>new TaskAttemptDto(a.Id,a.AttemptNumber,a.AttemptType,a.Status,a.Provider,a.Model,a.PromptVersion,a.InputTokenCount,a.OutputTokenCount,a.ToolStepCount,a.Summary,a.FailureCode,a.FailureReason,Deserialize(a.ChangedFilesJson),a.PatchArtifactReference,a.PatchSha256,Deserialize(a.ValidationSummaryJson),a.StartedAtUtc,a.CompletedAtUtc)).ToList(),t.ReviewDecisions.Select(x=>new ReviewDecisionDto(x.Id,x.TaskAttemptId,x.Decision,x.Provider,x.Model,x.PromptVersion,x.InputTokenCount,x.OutputTokenCount,x.ReviewedPatchSha256,x.Summary,x.Feedback,x.FindingsJson,x.IsCurrent,x.CreatedAtUtc)).ToList(),t.SkipReason,t.FailureReason,DeserializeGuids(t.DependsOnTaskIdsJson),Deserialize(t.AffectedAreasJson),t.ChangeType,t.Risk,t.ConflictRisk,t.ExecutionReason,Deserialize(t.RepositoryEvidenceJson),t.OriginalPlannerSequence,t.OrderAdjusted,t.OrderAdjustmentReason,t.EstablishesSharedContract)).ToList(),(attempts??[]).Select(a=>new PlanningAttemptDto(a.AttemptNumber,a.Provider,a.Model,a.PromptVersion,a.Status,a.StartedAtUtc,a.CompletedAtUtc,a.FailureCode,a.FailureMessage,a.InputTokenCount,a.OutputTokenCount)).ToList(),r.InfrastructureFailureCode,r.InfrastructureFailureMessage,r.InfrastructureBlockedTaskId);
 private static IReadOnlyList<string> Deserialize(string json){try{return JsonSerializer.Deserialize<List<string>>(json)??[];}catch{return [];}}
 private static IReadOnlyList<Guid> DeserializeGuids(string json){try{return JsonSerializer.Deserialize<List<Guid>>(json)??[];}catch{return [];}}
 private static PipelineEventDto Map(PipelineRunEvent e)=>new(e.Id,e.PlannedTaskId,e.EventType,e.PreviousState,e.NewState,e.Message,e.CreatedAtUtc,e.Sequence);
}
