using Impersonate.Domain.Pipelines;
using Impersonate.Domain.Projects;

namespace Impersonate.Application.Pipelines;

public sealed record CreatePipelineRunRequest(string FeatureRequest);
public sealed record PipelineOptions { public int MaximumRevisionAttempts { get; init; } = 3; public bool ContinueOnTaskFailure { get; init; } = true; }
public sealed record LoopRunDto(Guid Id,string LoopDefinitionId,string LoopDefinitionVersion,LoopRunStatus Status,LoopStage CurrentStage,int MaximumRevisionAttempts,bool ContinueOnTaskFailure,int RetryCount,DateTimeOffset? StartedAtUtc,DateTimeOffset? CompletedAtUtc,string? StopReason,string? FailureReason);
public sealed record PlannedTaskDto(Guid Id,int Sequence,string Title,string Description,IReadOnlyList<string> AcceptanceCriteria,PlannedTaskStatus Status,int RevisionCount,int MaximumRevisionAttempts,int AttemptCount,ReviewDecisionType? CurrentReview,string? SkipReason,string? FailureReason);
public sealed record PlanningAttemptDto(int AttemptNumber,string Provider,string Model,string PromptVersion,PlanningAttemptStatus Status,DateTimeOffset StartedAtUtc,DateTimeOffset? CompletedAtUtc,string? FailureMessage);
public sealed record PipelineRunDto(Guid Id,Guid ProjectId,string FeatureRequest,PipelineRunStatus Status,DateTimeOffset CreatedAtUtc,DateTimeOffset? StartedAtUtc,DateTimeOffset? CompletedAtUtc,DateTimeOffset? CancelledAtUtc,string? FailureReason,string? StopReason,LoopRunDto Loop,IReadOnlyList<PlannedTaskDto> Tasks,IReadOnlyList<PlanningAttemptDto> PlanningAttempts);
public sealed record PipelineEventDto(Guid Id,Guid? PlannedTaskId,string EventType,string? PreviousState,string NewState,string Message,DateTimeOffset CreatedAtUtc,int Sequence);
public sealed record PipelineOperationResult<T>(T? Value,string? Error,string? Code) { public bool Succeeded => Error is null; public static PipelineOperationResult<T> Ok(T value)=>new(value,null,null); public static PipelineOperationResult<T> Fail(string code,string error)=>new(default,error,code); }
public interface IPipelineRunRepository { Task AddAsync(PipelineRun run,CancellationToken ct); Task<PipelineRun?> GetAsync(Guid projectId,Guid runId,CancellationToken ct); Task<IReadOnlyList<PlanningAttempt>> GetPlanningAttemptsAsync(Guid runId,CancellationToken ct); Task<IReadOnlyList<PipelineRun>> ListAsync(Guid projectId,PipelineRunStatus? status,DateTimeOffset? from,DateTimeOffset? to,CancellationToken ct); Task SaveChangesAsync(CancellationToken ct); }
public interface IPipelineRunService { Task<PipelineOperationResult<PipelineRunDto>> CreateAsync(Guid projectId,CreatePipelineRunRequest request,CancellationToken ct); Task<PipelineRunDto?> GetAsync(Guid projectId,Guid runId,CancellationToken ct); Task<IReadOnlyList<PipelineRunDto>> ListAsync(Guid projectId,PipelineRunStatus? status,DateTimeOffset? from,DateTimeOffset? to,CancellationToken ct); Task<IReadOnlyList<PipelineEventDto>?> TimelineAsync(Guid projectId,Guid runId,CancellationToken ct); Task<PipelineOperationResult<PipelineRunDto>> StartPlanningAsync(Guid projectId,Guid runId,CancellationToken ct); Task<PipelineOperationResult<PipelineRunDto>> CancelAsync(Guid projectId,Guid runId,CancellationToken ct); }
public sealed record LoopDefinition(string Id,string Name,string Version,IReadOnlyList<LoopStage> Stages,int MaximumRevisionAttempts,bool ContinueOnTaskFailure);
public interface ILoopDefinitionRegistry { LoopDefinition Get(string id,string? version=null); }
