import { useEffect, useState, type FormEvent } from 'react';
import { Alert, Box, Button, Card, CardContent, Chip, CircularProgress, Dialog, DialogActions, DialogContent, DialogContentText, DialogTitle, MenuItem, Stack, TextField, Typography } from '@mui/material';
import { Link, Navigate, Outlet, useNavigate, useParams } from 'react-router-dom';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { changeProjectStatus, createProject, getProject, getProjectHealth, listProjects, updateProject, type ProjectInput, type ProjectStatus } from '../api/projectsApi';
import { useActiveProject } from '../ActiveProjectContext';
const statuses: ProjectStatus[] = ['Active', 'Idle', 'Off'];
const defaultInput: ProjectInput = { name: '', description: '', repositoryUrl: '', defaultBranch: 'main', status: 'Idle' };
export function ProjectsPage() { const [search, setSearch] = useState(''); const [status, setStatus] = useState<ProjectStatus | ''>(''); const projects = useQuery({ queryKey: ['projects', status, search], queryFn: () => listProjects(status || undefined, search || undefined) }); const { setActiveProject } = useActiveProject(); const navigate = useNavigate(); if (projects.isLoading) return <CircularProgress />; if (projects.isError) return <Alert severity="error">{projects.error.message}</Alert>; return <Stack spacing={3}><Stack direction="row" justifyContent="space-between"><Typography variant="h4">Projects</Typography><Button component={Link} to="/projects/new" variant="contained">Create project</Button></Stack><Stack direction={{ xs: 'column', sm: 'row' }} spacing={2}><TextField label="Search projects" value={search} onChange={(e) => setSearch(e.target.value)} /><TextField select label="Status" value={status} onChange={(e) => setStatus(e.target.value as ProjectStatus | '')} sx={{ minWidth: 140 }}><MenuItem value="">All statuses</MenuItem>{statuses.map(s => <MenuItem key={s} value={s}>{s}</MenuItem>)}</TextField></Stack>{projects.data?.length === 0 ? <Alert severity="info">No projects match this view. Create a project to establish a workspace.</Alert> : projects.data?.map(project => <Card key={project.id}><CardContent><Stack direction={{ xs: 'column', md: 'row' }} justifyContent="space-between" spacing={2}><Box><Typography variant="h6">{project.name} <Chip size="small" label={project.status} color={project.status === 'Active' ? 'success' : project.status === 'Off' ? 'default' : 'warning'} /></Typography><Typography color="text.secondary">{project.description || 'No description provided.'}</Typography><Typography variant="body2">{project.repositoryUrl} · {project.defaultBranch}</Typography></Box><Stack direction="row" spacing={1}><Button onClick={() => { setActiveProject(project.id); navigate(`/projects/${project.id}/dashboard`); }}>Open</Button><Button component={Link} to={`/projects/${project.id}/settings`}>Edit</Button></Stack></Stack></CardContent></Card>)}</Stack>; }
export function ProjectWorkspaceLayout() { const { projectId } = useParams(); const { activeProjectId, setActiveProject } = useActiveProject(); const project = useQuery({ queryKey: ['project', projectId], queryFn: ({ signal }) => getProject(projectId!, signal), enabled: !!projectId, retry: false }); useEffect(() => { if (project.data && activeProjectId !== projectId) setActiveProject(project.data.id); }, [activeProjectId, project.data, projectId, setActiveProject]); if (!projectId || project.isError) return <Navigate to="/projects" replace />; if (project.isLoading) return <CircularProgress />; return <Stack spacing={3}><Stack direction={{ xs: 'column', sm: 'row' }} justifyContent="space-between"><Box><Typography variant="overline">Project workspace</Typography><Typography variant="h5">{project.data?.name} <Chip size="small" label={project.data?.status} /></Typography></Box><Stack direction="row" spacing={1}><Button component={Link} to="dashboard">Dashboard</Button><Button component={Link} to="runs">Runs</Button><Button component={Link} to="settings">Settings</Button><Button component={Link} to="health">Configuration health</Button></Stack></Stack><Outlet /></Stack>; }
export function ProjectDashboardPage() { const { projectId } = useParams(); const project = useQuery({ queryKey: ['project', projectId], queryFn: () => getProject(projectId!), enabled: !!projectId }); const health = useQuery({ queryKey: ['project-health', projectId], queryFn: () => getProjectHealth(projectId!), enabled: !!projectId }); if (project.isLoading) return <CircularProgress />; if (project.isError || !project.data) return <Alert severity="error">This project is unavailable.</Alert>; const currentProject = project.data; return <Stack spacing={2}><Typography variant="h4">{currentProject.name}</Typography><Card><CardContent><Typography>Repository: {currentProject.repositoryUrl}</Typography><Typography>Branch: {currentProject.defaultBranch}</Typography><Typography>Operational state: <Chip size="small" label={currentProject.status} /></Typography></CardContent></Card><Card><CardContent><Typography variant="h6">Configuration Health</Typography><Typography>{health.data?.overallStatus ?? 'Loading…'} — configuration only; repository connectivity is not checked.</Typography></CardContent></Card><Alert severity="info">No pipeline runs have been created for this project. Pipeline execution will be added in a later milestone.</Alert></Stack>; }
function ProjectForm({ projectId }: { projectId?: string }) { const navigate = useNavigate(); const client = useQueryClient(); const current = useQuery({ queryKey: ['project', projectId], queryFn: ({ signal }) => getProject(projectId!, signal), enabled: !!projectId }); const [input, setInput] = useState<ProjectInput>(defaultInput); useEffect(() => { if (current.data) setInput({ name: current.data.name, description: current.data.description, repositoryUrl: current.data.repositoryUrl, defaultBranch: current.data.defaultBranch, status: current.data.status }); }, [current.data]); const mutation = useMutation({ mutationFn: (value: ProjectInput) => projectId ? updateProject(projectId, value) : createProject(value), onSuccess: (project) => { client.invalidateQueries({ queryKey: ['projects'] }); client.setQueryData(['project', project.id], project); navigate(`/projects/${project.id}/dashboard`); } }); const submit = (e: FormEvent) => { e.preventDefault(); mutation.mutate(input); }; const set = (field: keyof ProjectInput, value: string) => setInput(previous => ({ ...previous, [field]: value })); if (current.isLoading) return <CircularProgress />; if (current.isError) return <Alert severity="error">This project is unavailable.</Alert>; return <Box component="form" onSubmit={submit}><Stack spacing={2}><TextField required label="Name" value={input.name} onChange={e => set('name', e.target.value)} inputProps={{ maxLength: 150 }} /><TextField label="Description" multiline value={input.description ?? ''} onChange={e => set('description', e.target.value)} inputProps={{ maxLength: 2000 }} /><TextField required label="Repository URL" type="url" helperText="GitHub HTTPS repository URL" value={input.repositoryUrl} onChange={e => set('repositoryUrl', e.target.value)} inputProps={{ maxLength: 500, pattern: 'https://github\\.com/[^/]+/[^/]+/?' }} /><TextField required label="Default branch" value={input.defaultBranch} onChange={e => set('defaultBranch', e.target.value)} inputProps={{ maxLength: 200 }} />{!projectId && <TextField select label="Initial status" value={input.status} onChange={e => set('status', e.target.value)}>{statuses.map(s => <MenuItem key={s} value={s}>{s}</MenuItem>)}</TextField>}{mutation.isError && <Alert severity="error">{mutation.error.message}</Alert>}<Button type="submit" variant="contained" disabled={mutation.isPending}>{mutation.isPending ? 'Saving…' : projectId ? 'Save changes' : 'Create project'}</Button></Stack></Box>; }
export function CreateProjectPage() { return <Stack spacing={2}><Typography variant="h4">Create project</Typography><ProjectForm /></Stack>; }
export function ProjectSettingsPage() {
  const { projectId } = useParams(); const [offConfirmationOpen, setOffConfirmationOpen] = useState(false);
  const project = useQuery({ queryKey: ['project', projectId], queryFn: () => getProject(projectId!), enabled: !!projectId }); const client = useQueryClient();
  const status = useMutation({ mutationFn: (value: ProjectStatus) => changeProjectStatus(projectId!, value), onSuccess: p => { client.setQueryData(['project', projectId], p); client.invalidateQueries({ queryKey: ['projects'] }); } });
  if (!projectId || project.isLoading) return <CircularProgress />;
  const setStatus = (value: ProjectStatus) => value === 'Off' ? setOffConfirmationOpen(true) : status.mutate(value);
  return <Stack spacing={3}><Typography variant="h4">Project settings</Typography><ProjectForm projectId={projectId} /><Card><CardContent><Typography variant="h6">Operational state</Typography><Stack direction="row" spacing={1}>{statuses.map(s => <Button key={s} disabled={s === project.data?.status} onClick={() => setStatus(s)}>{s}</Button>)}</Stack><Typography variant="body2">ID: {project.data?.id}<br />Created: {project.data?.createdAtUtc}<br />Updated: {project.data?.updatedAtUtc}</Typography></CardContent></Card><Dialog open={offConfirmationOpen} onClose={() => setOffConfirmationOpen(false)}><DialogTitle>Turn project Off?</DialogTitle><DialogContent><DialogContentText>Future automation will be disabled, but configuration and history will be retained.</DialogContentText></DialogContent><DialogActions><Button onClick={() => setOffConfirmationOpen(false)}>Cancel</Button><Button color="warning" onClick={() => { status.mutate('Off'); setOffConfirmationOpen(false); }}>Turn Off</Button></DialogActions></Dialog></Stack>;
}
export function ProjectHealthPage() { const { projectId } = useParams(); const health = useQuery({ queryKey: ['project-health', projectId], queryFn: () => getProjectHealth(projectId!), enabled: !!projectId }); if (health.isLoading) return <CircularProgress />; if (health.isError) return <Alert severity="error">{health.error.message}</Alert>; return <Stack spacing={2}><Typography variant="h4">Configuration Health</Typography><Typography>This validates stored configuration only; it does not prove the repository is reachable.</Typography>{health.data?.checks.map(c => <Card key={c.name}><CardContent><Typography>{c.name} — <Chip size="small" label={c.status} /></Typography><Typography color="text.secondary">{c.message}</Typography></CardContent></Card>)}<Typography variant="caption">Checked {health.data?.checkedAtUtc}</Typography></Stack>; }
