namespace Impersonate.Application.Planning;
public sealed record PlannerOptions { public string Provider{get;init;}="Anthropic"; public string Model{get;init;}=""; public string PromptVersion{get;init;}="planner-v1"; public int MaximumTasks{get;init;}=12; public int MaximumPlanningAttempts{get;init;}=2; public int TimeoutSeconds{get;init;}=120; public int PollIntervalSeconds{get;init;}=5; }
public sealed record PlannerAgentRequest(Guid ProjectId,string ProjectName,string? ProjectDescription,string RepositoryUrl,string DefaultBranch,string FeatureRequest,int MaximumTasks,string PromptVersion,string? CorrectionContext=null);
public sealed record PlannerTask(int Sequence,string Title,string Description,IReadOnlyList<string> AcceptanceCriteria);
public sealed record PlannerPlan(string Summary,bool CanPlan,IReadOnlyList<string> PlanningNotes,IReadOnlyList<PlannerTask> Tasks,string? FailureReason,string? ClarifyingQuestion);
public sealed record PlannerAgentResult(PlannerPlan Plan,string? ProviderRequestId,int? InputTokenCount,int? OutputTokenCount);
public interface IPlannerAgent { Task<PlannerAgentResult> PlanAsync(PlannerAgentRequest request,CancellationToken cancellationToken); }
public sealed record LanguageModelRequest(string Model,string SystemInstructions,string UserContent,string JsonSchema);
public sealed record LanguageModelResponse(string Content,string? ProviderRequestId,int? InputTokenCount,int? OutputTokenCount);
public interface ILanguageModelClient { Task<LanguageModelResponse> CompleteAsync(LanguageModelRequest request,CancellationToken cancellationToken); }
public static class PlannerPlanValidator { public static IReadOnlyList<string> Validate(PlannerPlan plan,int max){var e=new List<string>();if(!plan.CanPlan){if(string.IsNullOrWhiteSpace(plan.FailureReason))e.Add("Failure reason is required.");if(string.IsNullOrWhiteSpace(plan.ClarifyingQuestion))e.Add("Clarifying question is required.");if(plan.Tasks.Count>0)e.Add("Unplannable responses cannot contain tasks.");return e;}if(plan.Tasks.Count is 0)e.Add("At least one task is required.");if(plan.Tasks.Count>max)e.Add($"Maximum task count is {max}.");if(!plan.Tasks.Select(x=>x.Sequence).SequenceEqual(Enumerable.Range(1,plan.Tasks.Count)))e.Add("Sequences must be contiguous from 1.");if(plan.Tasks.GroupBy(x=>x.Title.Trim(),StringComparer.OrdinalIgnoreCase).Any(g=>g.Count()>1))e.Add("Task titles must be unique.");if(plan.Tasks.Any(x=>string.IsNullOrWhiteSpace(x.Title)||x.Title.Length>200||string.IsNullOrWhiteSpace(x.Description)||x.Description.Length>4000))e.Add("Task title or description is invalid.");if(plan.Tasks.Any(x=>x.AcceptanceCriteria.Count==0||x.AcceptanceCriteria.Any(c=>string.IsNullOrWhiteSpace(c)||c.Length>500)))e.Add("Acceptance criteria are required and limited to 500 characters.");if(plan.Tasks.Any(x=>(x.Title+" "+x.Description).Contains("TODO",StringComparison.OrdinalIgnoreCase)))e.Add("Placeholder wording is not allowed.");return e;} }
