using Impersonate.Application.Planning;using Impersonate.Application.Projects;using Impersonate.Domain.AiModels;using Microsoft.Extensions.Options;
namespace Impersonate.Application.AiModels;
internal sealed class AgentModelResolver(IAiModelConfigurationRepository repo,IOptions<PlannerOptions> options,IProviderRuntimeStatus runtime):IAgentModelResolver{public async Task<ResolvedAgentModel?> ResolveAsync(AgentRole role,Guid? project,CancellationToken ct){if(project is not null&&await repo.GetAssignmentAsync(role,project,ct)is{}pa&&await repo.GetModelAsync(pa.AiModelProfileId,ct)is{}pm)return Map(pm,ModelResolutionSource.ProjectOverride);if(await repo.GetAssignmentAsync(role,null,ct)is{}ga&&await repo.GetModelAsync(ga.AiModelProfileId,ct)is{}gm)return Map(gm,ModelResolutionSource.GlobalDefault);var o=options.Value;if(role==AgentRole.Planner&&!string.IsNullOrWhiteSpace(o.Provider)&&!string.IsNullOrWhiteSpace(o.Model))return new(o.Provider,o.Model,null,null,ModelResolutionSource.EnvironmentFallback,true,runtime.IsSupported(o.Provider));return null;}private ResolvedAgentModel Map(AiModelProfile m,ModelResolutionSource source)=>new(m.Provider,m.ModelIdentifier,m.DisplayName,m.Id,source,m.IsEnabled,runtime.IsSupported(m.Provider));}
internal sealed class AiModelConfigurationService(IAiModelConfigurationRepository repo,IProjectRepository projects,IAgentModelResolver resolver,IProviderRuntimeStatus runtime):IAiModelConfigurationService
{
 public async Task<IReadOnlyList<AiModelProfileDto>> ListModelsAsync(CancellationToken ct)=>(await repo.ListModelsAsync(ct)).Select(Map).ToList();
 public async Task<AiModelResult<AiModelProfileDto>> SaveModelAsync(Guid? id,AiModelProfileRequest r,CancellationToken ct){try{var duplicate=await repo.FindModelAsync(r.Provider.Trim(),r.ModelIdentifier.Trim(),ct);if(duplicate is not null&&duplicate.Id!=id)return AiModelResult<AiModelProfileDto>.Fail("duplicate_model","A model with this provider and identifier already exists.");AiModelProfile model;if(id is null){model=AiModelProfile.Create(r.DisplayName,r.Provider,r.ModelIdentifier,r.Description,r.IsEnabled);await repo.AddModelAsync(model,ct);}else{model=await repo.GetModelAsync(id.Value,ct)??throw new KeyNotFoundException();model.Update(r.DisplayName,r.Provider,r.ModelIdentifier,r.Description);model.SetEnabled(r.IsEnabled);}await repo.SaveChangesAsync(ct);return AiModelResult<AiModelProfileDto>.Ok(Map(model));}catch(KeyNotFoundException){return AiModelResult<AiModelProfileDto>.Fail("not_found","AI model was not found.");}catch(ArgumentException ex){return AiModelResult<AiModelProfileDto>.Fail("validation",ex.Message);}}
 public async Task<AiModelResult<AiModelProfileDto>> SetEnabledAsync(Guid id,bool enabled,CancellationToken ct){var m=await repo.GetModelAsync(id,ct);if(m is null)return AiModelResult<AiModelProfileDto>.Fail("not_found","AI model was not found.");m.SetEnabled(enabled);await repo.SaveChangesAsync(ct);return AiModelResult<AiModelProfileDto>.Ok(Map(m));}
 public async Task<IReadOnlyList<AgentModelAssignmentDto>> ListAssignmentsAsync(Guid? project,CancellationToken ct){var models=(await repo.ListModelsAsync(ct)).ToDictionary(x=>x.Id);return (await repo.ListAssignmentsAsync(project,ct)).Select(a=>Map(a,models[a.AiModelProfileId])).ToList();}
 public async Task<AiModelResult<AgentModelAssignmentDto>> SetAssignmentAsync(AgentRole role,Guid modelId,Guid? project,CancellationToken ct){if(project is not null&&await projects.GetAsync(project.Value,ct)is null)return AiModelResult<AgentModelAssignmentDto>.Fail("not_found","Project was not found.");var m=await repo.GetModelAsync(modelId,ct);if(m is null)return AiModelResult<AgentModelAssignmentDto>.Fail("not_found","AI model was not found.");if(!m.IsEnabled)return AiModelResult<AgentModelAssignmentDto>.Fail("model_disabled","Disabled models cannot be assigned.");if(!runtime.IsSupported(m.Provider))return AiModelResult<AgentModelAssignmentDto>.Fail("provider_unsupported","This provider has no executable adapter.");var a=await repo.GetAssignmentAsync(role,project,ct);if(a is null){a=AgentModelAssignment.Create(role,modelId,project);await repo.AddAssignmentAsync(a,ct);}else a.ReplaceModel(modelId);await repo.SaveChangesAsync(ct);return AiModelResult<AgentModelAssignmentDto>.Ok(Map(a,m));}
 public async Task<AiModelResult<bool>> RemoveAssignmentAsync(AgentRole role,Guid? project,CancellationToken ct){if(project is not null&&await projects.GetAsync(project.Value,ct)is null)return AiModelResult<bool>.Fail("not_found","Project was not found.");var a=await repo.GetAssignmentAsync(role,project,ct);if(a is null)return AiModelResult<bool>.Fail("not_found","Assignment was not found.");repo.RemoveAssignment(a);await repo.SaveChangesAsync(ct);return AiModelResult<bool>.Ok(true);}
 public async Task<AiModelResult<IReadOnlyList<EffectiveAgentModelDto>>> EffectiveAsync(Guid? project,CancellationToken ct){if(project is not null&&await projects.GetAsync(project.Value,ct)is null)return AiModelResult<IReadOnlyList<EffectiveAgentModelDto>>.Fail("not_found","Project was not found.");var list=new List<EffectiveAgentModelDto>();foreach(var role in Enum.GetValues<AgentRole>()){var m=await resolver.ResolveAsync(role,project,ct);list.Add(m is null?new(role,null,null,null,null,ModelResolutionSource.Unconfigured,false,false,role==AgentRole.Planner,"No model is assigned."):new(role,m.Provider,m.ModelIdentifier,m.ModelDisplayName,m.AiModelProfileId,m.Source,m.ModelEnabled,m.ProviderSupported,role==AgentRole.Planner,m.Source.ToString()));}return AiModelResult<IReadOnlyList<EffectiveAgentModelDto>>.Ok(list);}
 public async Task<AiModelResult<PlannerReadinessDto>> ReadinessAsync(Guid? project,CancellationToken ct){if(project is not null&&await projects.GetAsync(project.Value,ct)is null)return AiModelResult<PlannerReadinessDto>.Fail("not_found","Project was not found.");var m=await resolver.ResolveAsync(AgentRole.Planner,project,ct);if(m is null)return AiModelResult<PlannerReadinessDto>.Ok(new("Incomplete",null,null,null,ModelResolutionSource.Unconfigured,false,false,false,"No Planner model is assigned."));var creds=runtime.CredentialsConfigured(m.Provider);var ready=m.ModelEnabled&&m.ProviderSupported&&creds;var message=!m.ModelEnabled?"The assigned model is disabled.":!m.ProviderSupported?"The selected provider is not supported.":!creds?$"{m.Provider} credentials are missing from the API host.":m.Source==ModelResolutionSource.ProjectOverride?"Planner configuration is ready. This project overrides the global Planner model.":m.Source==ModelResolutionSource.GlobalDefault?"Planner configuration is ready. This project inherits the global Planner model.":"Planner configuration is ready using the environment fallback.";return AiModelResult<PlannerReadinessDto>.Ok(new(ready?"Ready":"Unavailable",m.Provider,m.ModelDisplayName,m.ModelIdentifier,m.Source,m.ModelEnabled,m.ProviderSupported,creds,message));}
 private AiModelProfileDto Map(AiModelProfile m)=>new(m.Id,m.DisplayName,m.Provider,m.ModelIdentifier,m.Description,m.IsEnabled,runtime.IsSupported(m.Provider),m.CreatedAtUtc,m.UpdatedAtUtc);private static AgentModelAssignmentDto Map(AgentModelAssignment a,AiModelProfile m)=>new(a.AgentRole,a.ProjectId,m.Id,m.DisplayName,m.Provider,m.ModelIdentifier);
}
