using Impersonate.Domain.AiModels;
namespace Impersonate.Application.AiModels;
public enum ModelResolutionSource { ProjectOverride,GlobalDefault,EnvironmentFallback,Unconfigured }
public sealed record AiModelProfileRequest(string DisplayName,string Provider,string ModelIdentifier,string? Description,bool IsEnabled=true);
public sealed record AiModelProfileDto(Guid Id,string DisplayName,string Provider,string ModelIdentifier,string? Description,bool IsEnabled,bool ProviderSupported,DateTimeOffset CreatedAtUtc,DateTimeOffset UpdatedAtUtc);
public sealed record AgentModelAssignmentDto(AgentRole AgentRole,Guid? ProjectId,Guid AiModelProfileId,string DisplayName,string Provider,string ModelIdentifier);
public sealed record EffectiveAgentModelDto(AgentRole AgentRole,string? Provider,string? ModelIdentifier,string? ModelDisplayName,Guid? AiModelProfileId,ModelResolutionSource Source,bool ModelEnabled,bool ProviderSupported,bool Operational,string Message);
public sealed record ResolvedAgentModel(string Provider,string ModelIdentifier,string? ModelDisplayName,Guid? AiModelProfileId,ModelResolutionSource Source,bool ModelEnabled,bool ProviderSupported);
public sealed record PlannerReadinessDto(string Status,string? Provider,string? ModelDisplayName,string? ModelIdentifier,ModelResolutionSource Source,bool ModelEnabled,bool ProviderSupported,bool CredentialsConfigured,string Message){public bool IsReady=>Status=="Ready";}
public sealed record AiModelResult<T>(T? Value,string? Code,string? Error){public bool Succeeded=>Error is null;public static AiModelResult<T> Ok(T value)=>new(value,null,null);public static AiModelResult<T> Fail(string code,string error)=>new(default,code,error);}
public interface IAiModelConfigurationRepository{Task<IReadOnlyList<AiModelProfile>> ListModelsAsync(CancellationToken ct);Task<AiModelProfile?> GetModelAsync(Guid id,CancellationToken ct);Task<AiModelProfile?> FindModelAsync(string provider,string identifier,CancellationToken ct);Task AddModelAsync(AiModelProfile model,CancellationToken ct);Task<IReadOnlyList<AgentModelAssignment>> ListAssignmentsAsync(Guid? projectId,CancellationToken ct);Task<AgentModelAssignment?> GetAssignmentAsync(AgentRole role,Guid? projectId,CancellationToken ct);Task AddAssignmentAsync(AgentModelAssignment assignment,CancellationToken ct);void RemoveAssignment(AgentModelAssignment assignment);Task SaveChangesAsync(CancellationToken ct);}
public interface IProviderRuntimeStatus{bool IsSupported(string provider);bool CredentialsConfigured(string provider);}
public interface IAgentModelResolver{Task<ResolvedAgentModel?> ResolveAsync(AgentRole role,Guid? projectId,CancellationToken ct);}
public interface IAiModelConfigurationService{Task<IReadOnlyList<AiModelProfileDto>> ListModelsAsync(CancellationToken ct);Task<AiModelResult<AiModelProfileDto>> SaveModelAsync(Guid? id,AiModelProfileRequest request,CancellationToken ct);Task<AiModelResult<AiModelProfileDto>> SetEnabledAsync(Guid id,bool enabled,CancellationToken ct);Task<IReadOnlyList<AgentModelAssignmentDto>> ListAssignmentsAsync(Guid? projectId,CancellationToken ct);Task<AiModelResult<AgentModelAssignmentDto>> SetAssignmentAsync(AgentRole role,Guid modelId,Guid? projectId,CancellationToken ct);Task<AiModelResult<bool>> RemoveAssignmentAsync(AgentRole role,Guid? projectId,CancellationToken ct);Task<AiModelResult<IReadOnlyList<EffectiveAgentModelDto>>> EffectiveAsync(Guid? projectId,CancellationToken ct);Task<AiModelResult<PlannerReadinessDto>> ReadinessAsync(Guid? projectId,CancellationToken ct);}
