namespace Impersonate.Domain.Pipelines;

public enum PipelineRunStatus { Created, Planning, ReadyForExecution, WaitingForClarification, Executing, WaitingForInfrastructure, ReadyForDelivery, WaitingForApproval, Completed, CompletedWithSkippedTasks, Failed, Cancelled }
public enum PlannedTaskStatus { Pending, Coding, Reviewing, ChangesRequested, Approved, Committing, Committed, Skipped, Failed, Cancelled }
public enum TaskAttemptType { Initial, Revision }
public enum TaskAttemptStatus { Started, Completed, Failed, Cancelled }
public enum ReviewDecisionType { Approved, ChangesRequested }
public enum LoopRunStatus { Pending, Running, WaitingForApproval, Completed, Failed, Cancelled }
public enum LoopStage { Planning, Coding, Reviewing, Revising, Committing, Completing }
public enum PlanningAttemptStatus { Started, Succeeded, InvalidOutput, ProviderFailed, TimedOut, Cancelled }

public sealed class PipelineRun
{
    public const int FeatureRequestMaxLength = 4000;
    private readonly List<PlannedTask> tasks = [];
    private readonly List<PipelineRunEvent> events = [];
    private PipelineRun() { }
    private PipelineRun(Guid projectId, string request, int maxRevisions, bool continueOnFailure, DateTimeOffset now)
    {
        if (projectId == Guid.Empty) throw new ArgumentException("Project ID is required.", nameof(projectId));
        Id = Guid.NewGuid(); ProjectId = projectId; FeatureRequest = Required(request, FeatureRequestMaxLength); CreatedAtUtc = now;
        LoopRun = LoopRun.Create(Id, maxRevisions, continueOnFailure, now);
        AddEvent("PipelineCreated", null, Status.ToString(), "Pipeline run created.", now);
    }
    public Guid Id { get; private set; }
    public Guid ProjectId { get; private set; }
    public string FeatureRequest { get; private set; } = null!;
    public PipelineRunStatus Status { get; private set; } = PipelineRunStatus.Created;
    public DateTimeOffset CreatedAtUtc { get; private set; }
    public DateTimeOffset? StartedAtUtc { get; private set; }
    public DateTimeOffset? CompletedAtUtc { get; private set; }
    public DateTimeOffset? CancelledAtUtc { get; private set; }
    public string? FailureReason { get; private set; }
    public string? StopReason { get; private set; }
    [System.ComponentModel.DataAnnotations.MaxLength(100)] public string? InfrastructureFailureCode { get; private set; }
    [System.ComponentModel.DataAnnotations.MaxLength(1000)] public string? InfrastructureFailureMessage { get; private set; }
    public Guid? InfrastructureBlockedTaskId { get; private set; }
    public string? PlanningContextArtifactReference { get; private set; }
    public string? PlanningContextSummary { get; private set; }
    public string PlanningLanguagesJson { get; private set; } = "[]";
    public string PlanningFrameworksJson { get; private set; } = "[]";
    public Guid? PlanningClaimId { get; private set; }
    public DateTimeOffset? PlanningClaimedAtUtc { get; private set; }
    public DateTimeOffset? PlanningClaimExpiresAtUtc { get; private set; }
    public string? PlanningWorkerId { get; private set; }
    public Guid? ExecutionClaimId { get; private set; }
    public Guid? ExecutionClaimedTaskId { get; private set; }
    public DateTimeOffset? ExecutionClaimedAtUtc { get; private set; }
    public DateTimeOffset? ExecutionClaimExpiresAtUtc { get; private set; }
    public string? ExecutionWorkerId { get; private set; }
    public LoopRun LoopRun { get; private set; } = null!;
    public IReadOnlyList<PlannedTask> Tasks => tasks.OrderBy(x => x.Sequence).ToList().AsReadOnly();
    public IReadOnlyList<PipelineRunEvent> Events => events.OrderBy(x => x.Sequence).ToList().AsReadOnly();
    public static PipelineRun Create(Guid projectId, string request, int maxRevisions = 3, bool continueOnFailure = true, DateTimeOffset? now = null) => new(projectId, request, maxRevisions, continueOnFailure, now ?? DateTimeOffset.UtcNow);
    public void StartPlanning(DateTimeOffset? at = null) { EnsureActive(PipelineRunStatus.Created); Transition(PipelineRunStatus.Planning, "PlanningStarted", "Planning started.", at); LoopRun.Start(at); }
    public void ClaimPlanning(Guid claimId,string workerId,DateTimeOffset expiresAt,DateTimeOffset? at=null){if(Status!=PipelineRunStatus.Planning)throw Invalid("Pipeline is not planning.");var now=at??DateTimeOffset.UtcNow;if(PlanningClaimExpiresAtUtc>now)throw Invalid("Planning is already claimed.");PlanningClaimId=claimId;PlanningWorkerId=Required(workerId,200);PlanningClaimedAtUtc=now;PlanningClaimExpiresAtUtc=expiresAt;AddEvent("PlanningClaimed",null,Status.ToString(),"Planning work claimed.",now);}
    public void ClearPlanningClaim(){PlanningClaimId=null;PlanningWorkerId=null;PlanningClaimedAtUtc=null;PlanningClaimExpiresAtUtc=null;}
    public void RecordPlanningContext(string artifactReference,string summary,IReadOnlyList<string> languages,IReadOnlyList<string> frameworks){EnsureActive(PipelineRunStatus.Planning);PlanningContextArtifactReference=Required(artifactReference,500);PlanningContextSummary=Required(summary,2000);PlanningLanguagesJson=System.Text.Json.JsonSerializer.Serialize(languages);PlanningFrameworksJson=System.Text.Json.JsonSerializer.Serialize(frameworks);AddEvent("PlanningRepositoryContextBuilt",null,Status.ToString(),summary,null);}
    public PlannedTask AddTask(int sequence, string title, string description, DateTimeOffset? at = null) => AddTask(sequence,title,description,["The described work is complete."],at);
    public PlannedTask AddTask(int sequence, string title, string description, IReadOnlyList<string> acceptanceCriteria, DateTimeOffset? at = null) { if (Status != PipelineRunStatus.Planning) throw Invalid("Tasks can only be added while planning."); if (tasks.Any(x => x.Sequence == sequence)) throw Invalid("Task sequence must be unique."); var task = PlannedTask.Create(Id, sequence, title, description, acceptanceCriteria, LoopRun.MaximumRevisionAttempts, at); tasks.Add(task); AddEvent("TaskPlanned", null, task.Status.ToString(), $"Task {sequence} added.", at); return task; }
    public void MarkReadyForExecution(DateTimeOffset? at = null) { EnsureActive(PipelineRunStatus.Planning); if (tasks.Count == 0) throw Invalid("At least one task is required."); Transition(PipelineRunStatus.ReadyForExecution, "PlanningCompleted", "Planning completed.", at); LoopRun.MoveToCoding(); ClearPlanningClaim(); }
    public void RequireClarification(string reason, string question, DateTimeOffset? at = null) { EnsureActive(PipelineRunStatus.Planning); FailureReason = Required(reason, 2000); StopReason = Required(question, 1000); Transition(PipelineRunStatus.WaitingForClarification, "ClarificationRequired", StopReason, at); ClearPlanningClaim(); }
    public void StartExecution(DateTimeOffset? at = null) { EnsureActive(PipelineRunStatus.ReadyForExecution); if (tasks.Count == 0) throw Invalid("At least one task is required."); Transition(PipelineRunStatus.Executing, "ExecutionStarted", "Pipeline execution started.", at); }
    public PlannedTask ClaimNextTask(Guid claimId,string workerId,DateTimeOffset expiresAt,DateTimeOffset? at=null){EnsureActive(PipelineRunStatus.Executing);var now=at??DateTimeOffset.UtcNow;if(expiresAt<=now)throw new ArgumentOutOfRangeException(nameof(expiresAt),"Claim expiry must be in the future.");if(ExecutionClaimExpiresAtUtc>now)throw Invalid("Task execution is already claimed.");var active=tasks.SingleOrDefault(x=>x.Status is PlannedTaskStatus.Coding or PlannedTaskStatus.Reviewing);var task=active??tasks.OrderBy(x=>x.Sequence).FirstOrDefault(x=>!x.IsExecutionResolved)??throw Invalid("No executable task remains.");if(tasks.Where(x=>x.Sequence<task.Sequence).Any(x=>!x.IsExecutionResolved))throw Invalid("Prior tasks must be resolved first.");if(active is null){if(task.Status==PlannedTaskStatus.Pending)task.StartCoding(now);else if(task.Status==PlannedTaskStatus.ChangesRequested)task.StartRevision(now);else throw Invalid("Next task cannot start from its current state.");}ExecutionClaimId=claimId;ExecutionClaimedTaskId=task.Id;ExecutionWorkerId=Required(workerId,200);ExecutionClaimedAtUtc=now;ExecutionClaimExpiresAtUtc=expiresAt;if(task.Status==PlannedTaskStatus.Coding)LoopRun.MoveToCoding();else LoopRun.MoveToReviewing();AddEvent(active is null?"TaskExecutionClaimed":"TaskExecutionReclaimed",null,task.Status.ToString(),$"Task {task.Sequence} claimed for execution.",now,task.Id);return task;}
    public void MoveTaskToReview(PlannedTask task,DateTimeOffset? at=null){RequireClaimed(task);var previous=task.Status.ToString();task.SubmitForReview();LoopRun.MoveToReviewing();AddEvent("TaskReviewStarted",previous,task.Status.ToString(),$"Task {task.Sequence} submitted for review.",at,task.Id);}
    public ReviewDecision RecordReview(PlannedTask task,ReviewDecisionType decision,string summary,string? feedback=null,DateTimeOffset? at=null){RequireClaimed(task);var previous=task.Status.ToString();var review=task.Review(decision,summary,feedback,at);if(decision==ReviewDecisionType.ChangesRequested)LoopRun.MoveToRevising();AddEvent(decision==ReviewDecisionType.Approved?"TaskApproved":"TaskChangesRequested",previous,task.Status.ToString(),summary,at,task.Id);return review;}
    public void ResolveRetryExhaustion(PlannedTask task,string reason,DateTimeOffset? at=null){RequireClaimed(task);if(task.Status!=PlannedTaskStatus.ChangesRequested||task.RevisionCount<task.MaximumRevisionAttempts)throw Invalid("Task retry limit has not been reached.");if(LoopRun.ContinueOnTaskFailure){task.Skip(reason,at);AddEvent("TaskSkipped","ChangesRequested","Skipped",reason,at,task.Id);ClearExecutionClaim();TryMarkReadyForDelivery(at);}else{task.Fail(reason,at);AddEvent("TaskFailed","ChangesRequested","Failed",reason,at,task.Id);ClearExecutionClaim();Fail(reason,at);}}
    public void ResolveExecutionFailure(PlannedTask task,string reason,DateTimeOffset? at=null){RequireClaimed(task);var previous=task.Status.ToString();if(task.Status is not(PlannedTaskStatus.Coding or PlannedTaskStatus.Reviewing))throw Invalid("Only active execution can fail.");if(LoopRun.ContinueOnTaskFailure){task.Skip(reason,at);AddEvent("TaskSkipped",previous,"Skipped",reason,at,task.Id);ClearExecutionClaim();TryMarkReadyForDelivery(at);}else{task.Fail(reason,at);AddEvent("TaskFailed",previous,"Failed",reason,at,task.Id);ClearExecutionClaim();Fail(reason,at);}}
    public void BlockForInfrastructure(PlannedTask task,string code,string message,DateTimeOffset? at=null){RequireClaimed(task);if(task.Status!=PlannedTaskStatus.Coding)throw Invalid("Infrastructure blocking is allowed only before Coder execution.");task.RollbackExecutionStartForInfrastructure();InfrastructureFailureCode=Required(code,100);InfrastructureFailureMessage=Required(message,1000);InfrastructureBlockedTaskId=task.Id;ClearExecutionClaim();Transition(PipelineRunStatus.WaitingForInfrastructure,"ExecutionInfrastructureBlocked",InfrastructureFailureMessage,at);}
    public void RetryInfrastructure(DateTimeOffset? at=null){EnsureActive(PipelineRunStatus.WaitingForInfrastructure);if(InfrastructureBlockedTaskId is null)throw Invalid("No infrastructure-blocked task is available.");InfrastructureFailureCode=null;InfrastructureFailureMessage=null;InfrastructureBlockedTaskId=null;Transition(PipelineRunStatus.Executing,"ExecutionInfrastructureRetry","Execution resumed after infrastructure recovery.",at);}
    public void FinishApprovedTask(PlannedTask task,DateTimeOffset? at=null){RequireClaimed(task);if(task.Status!=PlannedTaskStatus.Approved)throw Invalid("Task is not approved.");ClearExecutionClaim();TryMarkReadyForDelivery(at);}
    public void ClearExecutionClaim(){ExecutionClaimId=null;ExecutionClaimedTaskId=null;ExecutionWorkerId=null;ExecutionClaimedAtUtc=null;ExecutionClaimExpiresAtUtc=null;}
    public void TryMarkReadyForDelivery(DateTimeOffset? at=null){EnsureActive(PipelineRunStatus.Executing);if(tasks.Any(x=>!x.IsExecutionResolved))return;if(!tasks.Any(x=>x.Status==PlannedTaskStatus.Approved)){Fail("Execution ended without an approved task.",at);return;}Transition(PipelineRunStatus.ReadyForDelivery,"ExecutionCompleted","All executable tasks have been reviewed.",at);LoopRun.MoveToCommitting();ClearExecutionClaim();}
    public void Complete(DateTimeOffset? at = null) { EnsureActive(PipelineRunStatus.Executing); if (tasks.Any(x => !x.IsTerminal)) throw Invalid("All tasks must be terminal."); if (!tasks.Any(x => x.Status == PlannedTaskStatus.Committed)) throw Invalid("At least one task must be committed."); var status = tasks.Any(x => x.Status is PlannedTaskStatus.Skipped or PlannedTaskStatus.Failed) ? PipelineRunStatus.CompletedWithSkippedTasks : PipelineRunStatus.Completed; Transition(status, "PipelineCompleted", "Pipeline completed.", at); CompletedAtUtc = at ?? DateTimeOffset.UtcNow; LoopRun.Complete(at); }
    public void Fail(string reason, DateTimeOffset? at = null) { EnsureNotTerminal(); FailureReason = Required(reason, 2000); Transition(PipelineRunStatus.Failed, "PipelineFailed", FailureReason, at); CompletedAtUtc = at ?? DateTimeOffset.UtcNow; LoopRun.Fail(reason, at); }
    public void Cancel(DateTimeOffset? at = null) { EnsureNotTerminal(); foreach (var task in tasks.Where(x => !x.IsTerminal)) task.Cancel(at); ClearPlanningClaim(); ClearExecutionClaim(); Transition(PipelineRunStatus.Cancelled, "PipelineCancelled", "Pipeline cancelled.", at); CancelledAtUtc = CompletedAtUtc = at ?? DateTimeOffset.UtcNow; LoopRun.Cancel(at); }
    public void RecordTaskEvent(PlannedTask task, string type, string? previous, string next, string message, DateTimeOffset? at = null) => AddEvent(type, previous, next, message, at, task.Id);
    private void Transition(PipelineRunStatus next, string type, string message, DateTimeOffset? at) { var previous = Status.ToString(); Status = next; StartedAtUtc ??= next is PipelineRunStatus.Planning or PipelineRunStatus.Executing ? at ?? DateTimeOffset.UtcNow : null; AddEvent(type, previous, next.ToString(), message, at); }
    private void AddEvent(string type, string? previous, string next, string message, DateTimeOffset? at, Guid? taskId = null) => events.Add(PipelineRunEvent.Create(ProjectId, Id, taskId, type, previous, next, message, events.Count + 1, at));
    private void EnsureActive(PipelineRunStatus expected) { EnsureNotTerminal(); if (Status != expected) throw Invalid($"Expected {expected}; current state is {Status}."); }
    private void RequireClaimed(PlannedTask task){if(ExecutionClaimedTaskId!=task.Id)throw Invalid("Task is not claimed by this execution.");}
    private void EnsureNotTerminal() { if (Status is PipelineRunStatus.ReadyForDelivery or PipelineRunStatus.Completed or PipelineRunStatus.CompletedWithSkippedTasks or PipelineRunStatus.Failed or PipelineRunStatus.Cancelled) throw Invalid($"Pipeline is already terminal ({Status})."); }
    internal static string Required(string? value, int max) { var result = value?.Trim(); if (string.IsNullOrWhiteSpace(result)) throw new ArgumentException("Value is required."); if (result.Length > max) throw new ArgumentOutOfRangeException(nameof(value), $"Value must not exceed {max} characters."); return result; }
    internal static InvalidOperationException Invalid(string message) => new(message);
}

public sealed class PlannedTask
{
    private readonly List<TaskAttempt> attempts = []; private readonly List<ReviewDecision> reviewDecisions = [];
    private PlannedTask() { }
    internal static PlannedTask Create(Guid runId, int sequence, string title, string description, IReadOnlyList<string> criteria, int max, DateTimeOffset? at) { if (sequence <= 0) throw new ArgumentOutOfRangeException(nameof(sequence)); if (max is < 0 or > 20) throw new ArgumentOutOfRangeException(nameof(max));if(criteria.Count==0||criteria.Any(string.IsNullOrWhiteSpace))throw new ArgumentException("Acceptance criteria are required."); return new() { Id=Guid.NewGuid(), PipelineRunId=runId, Sequence=sequence, Title=PipelineRun.Required(title,200), Description=PipelineRun.Required(description,4000), AcceptanceCriteriaJson=System.Text.Json.JsonSerializer.Serialize(criteria.Select(x=>PipelineRun.Required(x,500))), MaximumRevisionAttempts=max, CreatedAtUtc=at??DateTimeOffset.UtcNow }; }
    public Guid Id { get; private set; } public Guid PipelineRunId { get; private set; } public int Sequence { get; private set; } public string Title { get; private set; }=null!; public string Description { get; private set; }=null!; public string AcceptanceCriteriaJson { get; private set; }="[]"; public IReadOnlyList<string> AcceptanceCriteria=>System.Text.Json.JsonSerializer.Deserialize<List<string>>(AcceptanceCriteriaJson)??[]; public PlannedTaskStatus Status { get; private set; } public int RevisionCount { get; private set; } public int MaximumRevisionAttempts { get; private set; } public Guid? CoderModelOverrideId{get;private set;} public Guid? ReviewerModelOverrideId{get;private set;} public string DependsOnTaskIdsJson{get;private set;}="[]";public string AffectedAreasJson{get;private set;}="[]";public string ChangeType{get;private set;}="Unknown";public string Risk{get;private set;}="Unknown";public string ConflictRisk{get;private set;}="Unknown";public string? ExecutionReason{get;private set;}public string RepositoryEvidenceJson{get;private set;}="[]";public int OriginalPlannerSequence{get;private set;}public bool OrderAdjusted{get;private set;}public string? OrderAdjustmentReason{get;private set;}public bool EstablishesSharedContract{get;private set;} public string? SkipReason { get; private set; } public string? FailureReason { get; private set; } public DateTimeOffset CreatedAtUtc { get; private set; } public DateTimeOffset? StartedAtUtc { get; private set; } public DateTimeOffset? CompletedAtUtc { get; private set; }
    public IReadOnlyList<TaskAttempt> Attempts => attempts.AsReadOnly(); public IReadOnlyList<ReviewDecision> ReviewDecisions => reviewDecisions.AsReadOnly(); public bool IsTerminal => Status is PlannedTaskStatus.Committed or PlannedTaskStatus.Skipped or PlannedTaskStatus.Failed or PlannedTaskStatus.Cancelled; public bool IsExecutionResolved=>Status is PlannedTaskStatus.Approved or PlannedTaskStatus.Skipped;
    public void SetModelOverrides(Guid? coder,Guid? reviewer){if(Status!=PlannedTaskStatus.Pending)throw PipelineRun.Invalid("Model overrides cannot change after execution starts.");CoderModelOverrideId=coder;ReviewerModelOverrideId=reviewer;}
    public void SetIntelligence(IReadOnlyList<Guid> dependencies,IReadOnlyList<string> affectedAreas,string changeType,string risk,string conflictRisk,string executionReason,IReadOnlyList<string> evidence,int originalSequence,bool adjusted,string? adjustmentReason,bool establishesContract){if(Status!=PlannedTaskStatus.Pending)throw PipelineRun.Invalid("Task intelligence is immutable after execution starts.");DependsOnTaskIdsJson=System.Text.Json.JsonSerializer.Serialize(dependencies);AffectedAreasJson=System.Text.Json.JsonSerializer.Serialize(affectedAreas.Take(30).Select(x=>PipelineRun.Required(x,300)));ChangeType=PipelineRun.Required(changeType,100);Risk=PipelineRun.Required(risk,30);ConflictRisk=PipelineRun.Required(conflictRisk,30);ExecutionReason=PipelineRun.Required(executionReason,1000);RepositoryEvidenceJson=System.Text.Json.JsonSerializer.Serialize(evidence.Take(30).Select(x=>PipelineRun.Required(x,500)));OriginalPlannerSequence=originalSequence;OrderAdjusted=adjusted;OrderAdjustmentReason=string.IsNullOrWhiteSpace(adjustmentReason)?null:PipelineRun.Required(adjustmentReason,1000);EstablishesSharedContract=establishesContract;}
    public TaskAttempt StartCoding(DateTimeOffset? at=null) { if (Status != PlannedTaskStatus.Pending) throw PipelineRun.Invalid("Only pending tasks can start coding."); Status=PlannedTaskStatus.Coding; StartedAtUtc=at??DateTimeOffset.UtcNow; return AddAttempt(TaskAttemptType.Initial,at); }
    public void CompleteAttempt(string summary, DateTimeOffset? at=null) { var a=attempts.LastOrDefault(x=>x.Status==TaskAttemptStatus.Started)??throw PipelineRun.Invalid("No active attempt."); a.Complete(summary,at); }
    public void SubmitForReview() { if(Status!=PlannedTaskStatus.Coding || attempts.LastOrDefault()?.Status!=TaskAttemptStatus.Completed) throw PipelineRun.Invalid("A completed coding attempt is required before review."); Status=PlannedTaskStatus.Reviewing; }
    public ReviewDecision Review(ReviewDecisionType decision,string summary,string? feedback=null,DateTimeOffset? at=null) { if(Status!=PlannedTaskStatus.Reviewing) throw PipelineRun.Invalid("Task is not awaiting review."); var attempt=attempts.Last(); if(reviewDecisions.Any(x=>x.TaskAttemptId==attempt.Id&&x.IsCurrent)) throw PipelineRun.Invalid("The attempt already has a current review."); if(decision==ReviewDecisionType.ChangesRequested && string.IsNullOrWhiteSpace(feedback)) throw new ArgumentException("Feedback is required when changes are requested.");foreach(var old in reviewDecisions.Where(x=>x.IsCurrent))old.Supersede(); var review=ReviewDecision.Create(Id,attempt.Id,decision,summary,feedback,at); reviewDecisions.Add(review); Status=decision==ReviewDecisionType.Approved?PlannedTaskStatus.Approved:PlannedTaskStatus.ChangesRequested; return review; }
    public TaskAttempt StartRevision(DateTimeOffset? at=null) { if(Status!=PlannedTaskStatus.ChangesRequested) throw PipelineRun.Invalid("Changes must be requested first."); if(RevisionCount>=MaximumRevisionAttempts) throw PipelineRun.Invalid("Retry limit reached."); RevisionCount++; Status=PlannedTaskStatus.Coding; return AddAttempt(TaskAttemptType.Revision,at); }
    internal void RollbackExecutionStartForInfrastructure(){if(Status!=PlannedTaskStatus.Coding)throw PipelineRun.Invalid("Task is not starting Coder execution.");var attempt=attempts.LastOrDefault()??throw PipelineRun.Invalid("No task attempt exists.");if(attempt.Status!=TaskAttemptStatus.Started||attempt.Provider is not null)throw PipelineRun.Invalid("Coder execution has already started.");attempts.Remove(attempt);if(attempt.AttemptType==TaskAttemptType.Revision){RevisionCount--;Status=PlannedTaskStatus.ChangesRequested;}else{Status=PlannedTaskStatus.Pending;StartedAtUtc=null;}}
    public void StartCommit() { if(Status!=PlannedTaskStatus.Approved || reviewDecisions.LastOrDefault()?.Decision!=ReviewDecisionType.Approved) throw PipelineRun.Invalid("Reviewer approval is required before commit."); Status=PlannedTaskStatus.Committing; }
    public void MarkCommitted(DateTimeOffset? at=null) { if(Status!=PlannedTaskStatus.Committing) throw PipelineRun.Invalid("Commit has not started."); Status=PlannedTaskStatus.Committed; CompletedAtUtc=at??DateTimeOffset.UtcNow; }
    public void Skip(string reason,DateTimeOffset? at=null) { if(IsTerminal) throw PipelineRun.Invalid("Task is already terminal."); SkipReason=PipelineRun.Required(reason,2000); Status=PlannedTaskStatus.Skipped; CompletedAtUtc=at??DateTimeOffset.UtcNow; }
    public void Fail(string reason,DateTimeOffset? at=null) { if(IsTerminal) throw PipelineRun.Invalid("Task is already terminal."); FailureReason=PipelineRun.Required(reason,2000); Status=PlannedTaskStatus.Failed; CompletedAtUtc=at??DateTimeOffset.UtcNow; }
    public void Cancel(DateTimeOffset? at=null) { if(IsTerminal)return; attempts.LastOrDefault(x=>x.Status==TaskAttemptStatus.Started)?.Cancel(at); Status=PlannedTaskStatus.Cancelled; CompletedAtUtc=at??DateTimeOffset.UtcNow; }
    private TaskAttempt AddAttempt(TaskAttemptType type,DateTimeOffset? at){var a=TaskAttempt.Create(Id,attempts.Count+1,type,at);attempts.Add(a);return a;}
}

public sealed class TaskAttempt { private TaskAttempt(){} public Guid Id{get;private set;} public Guid PlannedTaskId{get;private set;} public int AttemptNumber{get;private set;} public TaskAttemptType AttemptType{get;private set;} public TaskAttemptStatus Status{get;private set;} public string? Provider{get;private set;} public string? Model{get;private set;} public string? PromptVersion{get;private set;} public string? ProviderRequestId{get;private set;} public int? InputTokenCount{get;private set;} public int? OutputTokenCount{get;private set;} public int ToolStepCount{get;private set;} public string? Summary{get;private set;} public string? FailureCode{get;private set;} public string? FailureReason{get;private set;} public string ChangedFilesJson{get;private set;}="[]"; public string? PatchArtifactReference{get;private set;} public string? PatchSha256{get;private set;} public string ValidationSummaryJson{get;private set;}="[]"; public DateTimeOffset StartedAtUtc{get;private set;} public DateTimeOffset? CompletedAtUtc{get;private set;} internal static TaskAttempt Create(Guid id,int number,TaskAttemptType type,DateTimeOffset? at)=>new(){Id=Guid.NewGuid(),PlannedTaskId=id,AttemptNumber=number,AttemptType=type,Status=TaskAttemptStatus.Started,StartedAtUtc=at??DateTimeOffset.UtcNow}; public void RecordExecution(string provider,string model,string promptVersion,string? requestId,int? input,int? output,int toolSteps,string changedFilesJson,string patchReference,string patchSha256,string validationJson){if(Status!=TaskAttemptStatus.Started)throw PipelineRun.Invalid("Attempt is terminal.");if(toolSteps<0)throw new ArgumentOutOfRangeException(nameof(toolSteps));Provider=PipelineRun.Required(provider,50);Model=PipelineRun.Required(model,300);PromptVersion=PipelineRun.Required(promptVersion,50);ProviderRequestId=requestId?.Trim();InputTokenCount=input;OutputTokenCount=output;ToolStepCount=toolSteps;ChangedFilesJson=PipelineRun.Required(changedFilesJson,16000);PatchArtifactReference=PipelineRun.Required(patchReference,500);PatchSha256=PipelineRun.Required(patchSha256,64);ValidationSummaryJson=PipelineRun.Required(validationJson,16000);} internal void Complete(string summary,DateTimeOffset? at){if(Status!=TaskAttemptStatus.Started)throw PipelineRun.Invalid("Attempt is terminal.");Summary=PipelineRun.Required(summary,2000);Status=TaskAttemptStatus.Completed;CompletedAtUtc=at??DateTimeOffset.UtcNow;} public void Fail(string code,string reason,DateTimeOffset? at=null){if(Status!=TaskAttemptStatus.Started)throw PipelineRun.Invalid("Attempt is terminal.");FailureCode=PipelineRun.Required(code,100);FailureReason=PipelineRun.Required(reason,2000);Status=TaskAttemptStatus.Failed;CompletedAtUtc=at??DateTimeOffset.UtcNow;} internal void Cancel(DateTimeOffset? at){if(Status==TaskAttemptStatus.Started){Status=TaskAttemptStatus.Cancelled;CompletedAtUtc=at??DateTimeOffset.UtcNow;}} }
public sealed class ReviewDecision { private ReviewDecision(){} public Guid Id{get;private set;} public Guid PlannedTaskId{get;private set;} public Guid TaskAttemptId{get;private set;} public ReviewDecisionType Decision{get;private set;} public string? Provider{get;private set;} public string? Model{get;private set;} public string? PromptVersion{get;private set;} public string? ProviderRequestId{get;private set;} public int? InputTokenCount{get;private set;} public int? OutputTokenCount{get;private set;} public string? ReviewedPatchSha256{get;private set;} public string FindingsJson{get;private set;}="[]"; public string Summary{get;private set;}=null!; public string? Feedback{get;private set;} public DateTimeOffset CreatedAtUtc{get;private set;} public bool IsCurrent{get;private set;} internal static ReviewDecision Create(Guid task,Guid attempt,ReviewDecisionType decision,string summary,string? feedback,DateTimeOffset? at)=>new(){Id=Guid.NewGuid(),PlannedTaskId=task,TaskAttemptId=attempt,Decision=decision,Summary=PipelineRun.Required(summary,2000),Feedback=string.IsNullOrWhiteSpace(feedback)?null:PipelineRun.Required(feedback,4000),CreatedAtUtc=at??DateTimeOffset.UtcNow,IsCurrent=true}; public void RecordExecution(string provider,string model,string promptVersion,string? requestId,int? input,int? output,string patchSha256,string findingsJson){Provider=PipelineRun.Required(provider,50);Model=PipelineRun.Required(model,300);PromptVersion=PipelineRun.Required(promptVersion,50);ProviderRequestId=requestId?.Trim();InputTokenCount=input;OutputTokenCount=output;ReviewedPatchSha256=PipelineRun.Required(patchSha256,64);FindingsJson=PipelineRun.Required(findingsJson,16000);} internal void Supersede()=>IsCurrent=false; }
public sealed class LoopRun { private LoopRun(){} public Guid Id{get;private set;} public Guid PipelineRunId{get;private set;} public string LoopDefinitionId{get;private set;}="feature-delivery"; public string LoopDefinitionVersion{get;private set;}="1"; public LoopRunStatus Status{get;private set;} public LoopStage CurrentStage{get;private set;}=LoopStage.Planning; public int MaximumRevisionAttempts{get;private set;} public bool ContinueOnTaskFailure{get;private set;} public int RetryCount{get;private set;} public DateTimeOffset? StartedAtUtc{get;private set;} public DateTimeOffset? CompletedAtUtc{get;private set;} public string? StopReason{get;private set;} public string? FailureReason{get;private set;} internal static LoopRun Create(Guid run,int max,bool cont,DateTimeOffset at){if(max is<0 or>20)throw new ArgumentOutOfRangeException(nameof(max));return new(){Id=Guid.NewGuid(),PipelineRunId=run,MaximumRevisionAttempts=max,ContinueOnTaskFailure=cont};} internal void Start(DateTimeOffset? at){if(Status!=LoopRunStatus.Pending)throw PipelineRun.Invalid("Loop cannot start.");Status=LoopRunStatus.Running;StartedAtUtc=at??DateTimeOffset.UtcNow;} internal void MoveToCoding(){EnsureActive();CurrentStage=LoopStage.Coding;} internal void MoveToReviewing(){EnsureActive();CurrentStage=LoopStage.Reviewing;} internal void MoveToRevising(){EnsureActive();CurrentStage=LoopStage.Revising;RetryCount++;} internal void MoveToCommitting(){EnsureActive();CurrentStage=LoopStage.Committing;} internal void Complete(DateTimeOffset? at){EnsureActive();Status=LoopRunStatus.Completed;CurrentStage=LoopStage.Completing;CompletedAtUtc=at??DateTimeOffset.UtcNow;} internal void Fail(string reason,DateTimeOffset? at){EnsureActive();Status=LoopRunStatus.Failed;FailureReason=reason;CompletedAtUtc=at??DateTimeOffset.UtcNow;} internal void Cancel(DateTimeOffset? at){EnsureActive();Status=LoopRunStatus.Cancelled;StopReason="Cancelled";CompletedAtUtc=at??DateTimeOffset.UtcNow;} private void EnsureActive(){if(Status is LoopRunStatus.Completed or LoopRunStatus.Failed or LoopRunStatus.Cancelled)throw PipelineRun.Invalid("Loop is terminal.");} }
public sealed class PipelineRunEvent { private PipelineRunEvent(){} public Guid Id{get;private set;} public Guid ProjectId{get;private set;} public Guid PipelineRunId{get;private set;} public Guid? PlannedTaskId{get;private set;} public string EventType{get;private set;}=null!; public string? PreviousState{get;private set;} public string NewState{get;private set;}=null!; public string Message{get;private set;}=null!; public DateTimeOffset CreatedAtUtc{get;private set;} public int Sequence{get;private set;} internal static PipelineRunEvent Create(Guid project,Guid run,Guid? task,string type,string? previous,string next,string message,int sequence,DateTimeOffset? at)=>new(){Id=Guid.NewGuid(),ProjectId=project,PipelineRunId=run,PlannedTaskId=task,EventType=type,PreviousState=previous,NewState=next,Message=message,Sequence=sequence,CreatedAtUtc=at??DateTimeOffset.UtcNow}; }
