namespace Impersonate.Domain.Pipelines;

public enum PipelineRunStatus { Created, Planning, Executing, WaitingForApproval, Completed, CompletedWithSkippedTasks, Failed, Cancelled }
public enum PlannedTaskStatus { Pending, Coding, Reviewing, ChangesRequested, Approved, Committing, Committed, Skipped, Failed, Cancelled }
public enum TaskAttemptType { Initial, Revision }
public enum TaskAttemptStatus { Started, Completed, Failed, Cancelled }
public enum ReviewDecisionType { Approved, ChangesRequested }
public enum LoopRunStatus { Pending, Running, WaitingForApproval, Completed, Failed, Cancelled }
public enum LoopStage { Planning, Coding, Reviewing, Revising, Committing, Completing }

public sealed class PipelineRun
{
    public const int FeatureRequestMaxLength = 4000;
    private readonly List<PlannedTask> tasks = [];
    private readonly List<PipelineRunEvent> events = [];
    private PipelineRun() { }
    private PipelineRun(Guid projectId, string request, int maxRevisions, bool continueOnFailure, DateTimeOffset now)
    {
        if (projectId == Guid.Empty) throw new ArgumentException("Project ID is required.", nameof(projectId));
        Id = Guid.NewGuid(); ProjectId = projectId; FeatureRequest = Required(request, FeatureRequestMaxLength); CreatedAtUtc = now;
        LoopRun = LoopRun.Create(Id, maxRevisions, continueOnFailure, now);
        AddEvent("PipelineCreated", null, Status.ToString(), "Pipeline run created.", now);
    }
    public Guid Id { get; private set; }
    public Guid ProjectId { get; private set; }
    public string FeatureRequest { get; private set; } = null!;
    public PipelineRunStatus Status { get; private set; } = PipelineRunStatus.Created;
    public DateTimeOffset CreatedAtUtc { get; private set; }
    public DateTimeOffset? StartedAtUtc { get; private set; }
    public DateTimeOffset? CompletedAtUtc { get; private set; }
    public DateTimeOffset? CancelledAtUtc { get; private set; }
    public string? FailureReason { get; private set; }
    public string? StopReason { get; private set; }
    public LoopRun LoopRun { get; private set; } = null!;
    public IReadOnlyList<PlannedTask> Tasks => tasks.OrderBy(x => x.Sequence).ToList().AsReadOnly();
    public IReadOnlyList<PipelineRunEvent> Events => events.OrderBy(x => x.Sequence).ToList().AsReadOnly();
    public static PipelineRun Create(Guid projectId, string request, int maxRevisions = 3, bool continueOnFailure = true, DateTimeOffset? now = null) => new(projectId, request, maxRevisions, continueOnFailure, now ?? DateTimeOffset.UtcNow);
    public void StartPlanning(DateTimeOffset? at = null) { EnsureActive(PipelineRunStatus.Created); Transition(PipelineRunStatus.Planning, "PlanningStarted", "Planning started.", at); LoopRun.Start(at); }
    public PlannedTask AddTask(int sequence, string title, string description, DateTimeOffset? at = null) { if (Status != PipelineRunStatus.Planning) throw Invalid("Tasks can only be added while planning."); if (tasks.Any(x => x.Sequence == sequence)) throw Invalid("Task sequence must be unique."); var task = PlannedTask.Create(Id, sequence, title, description, LoopRun.MaximumRevisionAttempts, at); tasks.Add(task); AddEvent("TasksAdded", null, task.Status.ToString(), $"Task {sequence} added.", at); return task; }
    public void StartExecution(DateTimeOffset? at = null) { EnsureActive(PipelineRunStatus.Planning); if (tasks.Count == 0) throw Invalid("At least one task is required."); Transition(PipelineRunStatus.Executing, "ExecutionStarted", "Pipeline execution started.", at); }
    public void Complete(DateTimeOffset? at = null) { EnsureActive(PipelineRunStatus.Executing); if (tasks.Any(x => !x.IsTerminal)) throw Invalid("All tasks must be terminal."); if (!tasks.Any(x => x.Status == PlannedTaskStatus.Committed)) throw Invalid("At least one task must be committed."); var status = tasks.Any(x => x.Status is PlannedTaskStatus.Skipped or PlannedTaskStatus.Failed) ? PipelineRunStatus.CompletedWithSkippedTasks : PipelineRunStatus.Completed; Transition(status, "PipelineCompleted", "Pipeline completed.", at); CompletedAtUtc = at ?? DateTimeOffset.UtcNow; LoopRun.Complete(at); }
    public void Fail(string reason, DateTimeOffset? at = null) { EnsureNotTerminal(); FailureReason = Required(reason, 2000); Transition(PipelineRunStatus.Failed, "PipelineFailed", FailureReason, at); CompletedAtUtc = at ?? DateTimeOffset.UtcNow; LoopRun.Fail(reason, at); }
    public void Cancel(DateTimeOffset? at = null) { EnsureNotTerminal(); foreach (var task in tasks.Where(x => !x.IsTerminal)) task.Cancel(at); Transition(PipelineRunStatus.Cancelled, "PipelineCancelled", "Pipeline cancelled.", at); CancelledAtUtc = CompletedAtUtc = at ?? DateTimeOffset.UtcNow; LoopRun.Cancel(at); }
    public void RecordTaskEvent(PlannedTask task, string type, string? previous, string next, string message, DateTimeOffset? at = null) => AddEvent(type, previous, next, message, at, task.Id);
    private void Transition(PipelineRunStatus next, string type, string message, DateTimeOffset? at) { var previous = Status.ToString(); Status = next; StartedAtUtc ??= next is PipelineRunStatus.Planning or PipelineRunStatus.Executing ? at ?? DateTimeOffset.UtcNow : null; AddEvent(type, previous, next.ToString(), message, at); }
    private void AddEvent(string type, string? previous, string next, string message, DateTimeOffset? at, Guid? taskId = null) => events.Add(PipelineRunEvent.Create(ProjectId, Id, taskId, type, previous, next, message, events.Count + 1, at));
    private void EnsureActive(PipelineRunStatus expected) { EnsureNotTerminal(); if (Status != expected) throw Invalid($"Expected {expected}; current state is {Status}."); }
    private void EnsureNotTerminal() { if (Status is PipelineRunStatus.Completed or PipelineRunStatus.CompletedWithSkippedTasks or PipelineRunStatus.Failed or PipelineRunStatus.Cancelled) throw Invalid($"Pipeline is already terminal ({Status})."); }
    internal static string Required(string? value, int max) { var result = value?.Trim(); if (string.IsNullOrWhiteSpace(result)) throw new ArgumentException("Value is required."); if (result.Length > max) throw new ArgumentOutOfRangeException(nameof(value), $"Value must not exceed {max} characters."); return result; }
    internal static InvalidOperationException Invalid(string message) => new(message);
}

public sealed class PlannedTask
{
    private readonly List<TaskAttempt> attempts = []; private readonly List<ReviewDecision> reviewDecisions = [];
    private PlannedTask() { }
    internal static PlannedTask Create(Guid runId, int sequence, string title, string description, int max, DateTimeOffset? at) { if (sequence <= 0) throw new ArgumentOutOfRangeException(nameof(sequence)); if (max is < 0 or > 20) throw new ArgumentOutOfRangeException(nameof(max)); return new() { Id=Guid.NewGuid(), PipelineRunId=runId, Sequence=sequence, Title=PipelineRun.Required(title,200), Description=PipelineRun.Required(description,4000), MaximumRevisionAttempts=max, CreatedAtUtc=at??DateTimeOffset.UtcNow }; }
    public Guid Id { get; private set; } public Guid PipelineRunId { get; private set; } public int Sequence { get; private set; } public string Title { get; private set; }=null!; public string Description { get; private set; }=null!; public PlannedTaskStatus Status { get; private set; } public int RevisionCount { get; private set; } public int MaximumRevisionAttempts { get; private set; } public string? SkipReason { get; private set; } public string? FailureReason { get; private set; } public DateTimeOffset CreatedAtUtc { get; private set; } public DateTimeOffset? StartedAtUtc { get; private set; } public DateTimeOffset? CompletedAtUtc { get; private set; }
    public IReadOnlyList<TaskAttempt> Attempts => attempts.AsReadOnly(); public IReadOnlyList<ReviewDecision> ReviewDecisions => reviewDecisions.AsReadOnly(); public bool IsTerminal => Status is PlannedTaskStatus.Committed or PlannedTaskStatus.Skipped or PlannedTaskStatus.Failed or PlannedTaskStatus.Cancelled;
    public TaskAttempt StartCoding(DateTimeOffset? at=null) { if (Status != PlannedTaskStatus.Pending) throw PipelineRun.Invalid("Only pending tasks can start coding."); Status=PlannedTaskStatus.Coding; StartedAtUtc=at??DateTimeOffset.UtcNow; return AddAttempt(TaskAttemptType.Initial,at); }
    public void CompleteAttempt(string summary, DateTimeOffset? at=null) { var a=attempts.LastOrDefault(x=>x.Status==TaskAttemptStatus.Started)??throw PipelineRun.Invalid("No active attempt."); a.Complete(summary,at); }
    public void SubmitForReview() { if(Status!=PlannedTaskStatus.Coding || attempts.LastOrDefault()?.Status!=TaskAttemptStatus.Completed) throw PipelineRun.Invalid("A completed coding attempt is required before review."); Status=PlannedTaskStatus.Reviewing; }
    public ReviewDecision Review(ReviewDecisionType decision,string summary,string? feedback=null,DateTimeOffset? at=null) { if(Status!=PlannedTaskStatus.Reviewing) throw PipelineRun.Invalid("Task is not awaiting review."); var attempt=attempts.Last(); if(reviewDecisions.Any(x=>x.TaskAttemptId==attempt.Id&&x.IsCurrent)) throw PipelineRun.Invalid("The attempt already has a current review."); if(decision==ReviewDecisionType.ChangesRequested && string.IsNullOrWhiteSpace(feedback)) throw new ArgumentException("Feedback is required when changes are requested."); var review=ReviewDecision.Create(Id,attempt.Id,decision,summary,feedback,at); reviewDecisions.Add(review); Status=decision==ReviewDecisionType.Approved?PlannedTaskStatus.Approved:PlannedTaskStatus.ChangesRequested; return review; }
    public TaskAttempt StartRevision(DateTimeOffset? at=null) { if(Status!=PlannedTaskStatus.ChangesRequested) throw PipelineRun.Invalid("Changes must be requested first."); if(RevisionCount>=MaximumRevisionAttempts) throw PipelineRun.Invalid("Retry limit reached."); RevisionCount++; Status=PlannedTaskStatus.Coding; return AddAttempt(TaskAttemptType.Revision,at); }
    public void StartCommit() { if(Status!=PlannedTaskStatus.Approved || reviewDecisions.LastOrDefault()?.Decision!=ReviewDecisionType.Approved) throw PipelineRun.Invalid("Reviewer approval is required before commit."); Status=PlannedTaskStatus.Committing; }
    public void MarkCommitted(DateTimeOffset? at=null) { if(Status!=PlannedTaskStatus.Committing) throw PipelineRun.Invalid("Commit has not started."); Status=PlannedTaskStatus.Committed; CompletedAtUtc=at??DateTimeOffset.UtcNow; }
    public void Skip(string reason,DateTimeOffset? at=null) { if(IsTerminal) throw PipelineRun.Invalid("Task is already terminal."); SkipReason=PipelineRun.Required(reason,2000); Status=PlannedTaskStatus.Skipped; CompletedAtUtc=at??DateTimeOffset.UtcNow; }
    public void Fail(string reason,DateTimeOffset? at=null) { if(IsTerminal) throw PipelineRun.Invalid("Task is already terminal."); FailureReason=PipelineRun.Required(reason,2000); Status=PlannedTaskStatus.Failed; CompletedAtUtc=at??DateTimeOffset.UtcNow; }
    public void Cancel(DateTimeOffset? at=null) { if(IsTerminal)return; attempts.LastOrDefault(x=>x.Status==TaskAttemptStatus.Started)?.Cancel(at); Status=PlannedTaskStatus.Cancelled; CompletedAtUtc=at??DateTimeOffset.UtcNow; }
    private TaskAttempt AddAttempt(TaskAttemptType type,DateTimeOffset? at){var a=TaskAttempt.Create(Id,attempts.Count+1,type,at);attempts.Add(a);return a;}
}

public sealed class TaskAttempt { private TaskAttempt(){} public Guid Id{get;private set;} public Guid PlannedTaskId{get;private set;} public int AttemptNumber{get;private set;} public TaskAttemptType AttemptType{get;private set;} public TaskAttemptStatus Status{get;private set;} public DateTimeOffset StartedAtUtc{get;private set;} public DateTimeOffset? CompletedAtUtc{get;private set;} public string? Summary{get;private set;} public string? FailureReason{get;private set;} public string? OutputReference{get;private set;} internal static TaskAttempt Create(Guid id,int number,TaskAttemptType type,DateTimeOffset? at)=>new(){Id=Guid.NewGuid(),PlannedTaskId=id,AttemptNumber=number,AttemptType=type,Status=TaskAttemptStatus.Started,StartedAtUtc=at??DateTimeOffset.UtcNow}; internal void Complete(string summary,DateTimeOffset? at){if(Status!=TaskAttemptStatus.Started)throw PipelineRun.Invalid("Attempt is terminal.");Summary=PipelineRun.Required(summary,2000);Status=TaskAttemptStatus.Completed;CompletedAtUtc=at??DateTimeOffset.UtcNow;} internal void Cancel(DateTimeOffset? at){if(Status==TaskAttemptStatus.Started){Status=TaskAttemptStatus.Cancelled;CompletedAtUtc=at??DateTimeOffset.UtcNow;}} }
public sealed class ReviewDecision { private ReviewDecision(){} public Guid Id{get;private set;} public Guid PlannedTaskId{get;private set;} public Guid TaskAttemptId{get;private set;} public ReviewDecisionType Decision{get;private set;} public string Summary{get;private set;}=null!; public string? Feedback{get;private set;} public DateTimeOffset CreatedAtUtc{get;private set;} public bool IsCurrent{get;private set;} internal static ReviewDecision Create(Guid task,Guid attempt,ReviewDecisionType decision,string summary,string? feedback,DateTimeOffset? at)=>new(){Id=Guid.NewGuid(),PlannedTaskId=task,TaskAttemptId=attempt,Decision=decision,Summary=PipelineRun.Required(summary,2000),Feedback=string.IsNullOrWhiteSpace(feedback)?null:feedback.Trim(),CreatedAtUtc=at??DateTimeOffset.UtcNow,IsCurrent=true}; }
public sealed class LoopRun { private LoopRun(){} public Guid Id{get;private set;} public Guid PipelineRunId{get;private set;} public string LoopDefinitionId{get;private set;}="feature-delivery"; public string LoopDefinitionVersion{get;private set;}="1"; public LoopRunStatus Status{get;private set;} public LoopStage CurrentStage{get;private set;}=LoopStage.Planning; public int MaximumRevisionAttempts{get;private set;} public bool ContinueOnTaskFailure{get;private set;} public int RetryCount{get;private set;} public DateTimeOffset? StartedAtUtc{get;private set;} public DateTimeOffset? CompletedAtUtc{get;private set;} public string? StopReason{get;private set;} public string? FailureReason{get;private set;} internal static LoopRun Create(Guid run,int max,bool cont,DateTimeOffset at){if(max is<0 or>20)throw new ArgumentOutOfRangeException(nameof(max));return new(){Id=Guid.NewGuid(),PipelineRunId=run,MaximumRevisionAttempts=max,ContinueOnTaskFailure=cont};} internal void Start(DateTimeOffset? at){if(Status!=LoopRunStatus.Pending)throw PipelineRun.Invalid("Loop cannot start.");Status=LoopRunStatus.Running;StartedAtUtc=at??DateTimeOffset.UtcNow;} internal void Complete(DateTimeOffset? at){EnsureActive();Status=LoopRunStatus.Completed;CurrentStage=LoopStage.Completing;CompletedAtUtc=at??DateTimeOffset.UtcNow;} internal void Fail(string reason,DateTimeOffset? at){EnsureActive();Status=LoopRunStatus.Failed;FailureReason=reason;CompletedAtUtc=at??DateTimeOffset.UtcNow;} internal void Cancel(DateTimeOffset? at){EnsureActive();Status=LoopRunStatus.Cancelled;StopReason="Cancelled";CompletedAtUtc=at??DateTimeOffset.UtcNow;} private void EnsureActive(){if(Status is LoopRunStatus.Completed or LoopRunStatus.Failed or LoopRunStatus.Cancelled)throw PipelineRun.Invalid("Loop is terminal.");} }
public sealed class PipelineRunEvent { private PipelineRunEvent(){} public Guid Id{get;private set;} public Guid ProjectId{get;private set;} public Guid PipelineRunId{get;private set;} public Guid? PlannedTaskId{get;private set;} public string EventType{get;private set;}=null!; public string? PreviousState{get;private set;} public string NewState{get;private set;}=null!; public string Message{get;private set;}=null!; public DateTimeOffset CreatedAtUtc{get;private set;} public int Sequence{get;private set;} internal static PipelineRunEvent Create(Guid project,Guid run,Guid? task,string type,string? previous,string next,string message,int sequence,DateTimeOffset? at)=>new(){Id=Guid.NewGuid(),ProjectId=project,PipelineRunId=run,PlannedTaskId=task,EventType=type,PreviousState=previous,NewState=next,Message=message,Sequence=sequence,CreatedAtUtc=at??DateTimeOffset.UtcNow}; }
