import {useState} from 'react';
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {Alert,Box,Button,Card,CardActions,CardContent,Dialog,DialogActions,DialogContent,DialogTitle,Grid,TextField,Typography} from '@mui/material';
import {connectProvider,disableProvider,listProviders,removeProvider,syncProvider,validateProvider,type ProviderConnection,type ProviderType} from '../api/aiApi';

const providers:ProviderType[]=['Anthropic','OpenAI','GoogleGemini','OpenRouter'];
const label=(type:ProviderType)=>type==='GoogleGemini'?'Google Gemini':type;

export function AiProvidersPage(){
  const client=useQueryClient();const query=useQuery({queryKey:['ai-providers'],queryFn:listProviders});const [connect,setConnect]=useState<ProviderType>();const [apiKey,setApiKey]=useState('');
  const refresh=()=>Promise.all([client.invalidateQueries({queryKey:['ai-providers']}),client.invalidateQueries({queryKey:['project-ai-readiness']}),client.invalidateQueries({queryKey:['planner-model-preview']})]);
  const create=useMutation({mutationFn:()=>connectProvider(connect!,apiKey),onSuccess:()=>{setApiKey('');setConnect(undefined);return refresh();}});
  if(query.isLoading)return <Typography>Loading AI providers…</Typography>;
  return <Box><Typography variant="h4" gutterBottom>AI Providers</Typography><Typography color="text.secondary" sx={{mb:3}}>Connect provider access once. Impersonate discovers eligible models and selects one automatically. Manual choice is an advanced override.</Typography>{query.error&&<Alert severity="error">Providers could not be loaded.</Alert>}<Grid container spacing={2}>{providers.map(type=><Grid key={type} size={{xs:12,md:6}}><ProviderCard type={type} connection={query.data?.connections.find(x=>x.providerType===type)} refresh={refresh} open={()=>setConnect(type)}/></Grid>)}</Grid><Dialog open={!!connect} onClose={()=>setConnect(undefined)} fullWidth maxWidth="sm"><DialogTitle>Connect {connect&&label(connect)}</DialogTitle><DialogContent><Alert severity="info" sx={{mb:2}}>The credential is encrypted after submission and is never displayed again.</Alert><TextField autoFocus fullWidth type="password" label="API key" value={apiKey} onChange={event=>setApiKey(event.target.value)} autoComplete="new-password"/></DialogContent><DialogActions><Button onClick={()=>setConnect(undefined)}>Cancel</Button><Button variant="contained" disabled={!apiKey||create.isPending} onClick={()=>create.mutate()}>Save securely</Button></DialogActions></Dialog></Box>;
}

function ProviderCard({type,connection,refresh,open}:{type:ProviderType;connection?:ProviderConnection;refresh:()=>Promise<unknown>;open:()=>void}){
  const action=(operation:(id:string)=>Promise<unknown>)=>async()=>{await operation(connection!.id);await refresh();};
  return <Card variant="outlined"><CardContent><Typography variant="h6">{label(type)}</Typography><Typography color={connection?.status==='Connected'?'success.main':'text.secondary'}>{connection?.status??'Not connected'}</Typography>{connection&&<Box sx={{mt:2}}><Typography variant="body2">Last validated: {connection.lastValidatedAtUtc?new Date(connection.lastValidatedAtUtc).toLocaleString():'Never'}</Typography><Typography variant="body2">Available models: {connection.availableModelCount}</Typography><Typography variant="body2">Last synchronised: {connection.lastModelSyncAtUtc?new Date(connection.lastModelSyncAtUtc).toLocaleString():'Never'}</Typography>{connection.lastSafeFailureMessage&&<Alert severity="warning" sx={{mt:1}}>{connection.lastSafeFailureMessage}</Alert>}</Box>}</CardContent><CardActions>{!connection?<Button onClick={open}>Connect</Button>:<><Button onClick={action(validateProvider)}>Validate</Button><Button disabled={connection.status!=='Connected'} onClick={action(syncProvider)}>Synchronise models</Button><Button onClick={open}>Replace credentials</Button><Button onClick={action(disableProvider)}>Disable</Button><Button color="error" onClick={action(removeProvider)}>Remove</Button></>}</CardActions></Card>;
}
