using System.Globalization;
using System.Net;
using System.Net.Http.Headers;
using System.Text.Json;
using Impersonate.Application.Quality;
namespace Impersonate.Infrastructure.Quality;
internal sealed class SonarQubeProvider(HttpClient client,ISonarQubeEndpointPolicy endpoints):ICodeQualityProvider
{
 private const string Metrics="alert_status,coverage,new_coverage,bugs,vulnerabilities,code_smells,reliability_rating,security_rating,sqale_rating,duplicated_lines_density,ncloc,cognitive_complexity";
 public async Task<CodeQualityProviderResult> GetSummaryAsync(CodeQualityProviderRequest request,CancellationToken ct)
 {
  var allowed=await endpoints.ValidateAsync(request.BaseUri,ct);if(!allowed.Allowed)return CodeQualityProviderResult.Fail(allowed.Code!,allowed.Message!,ProjectQualityState.Failed);
  var baseUri=EnsureTrailingSlash(request.BaseUri);
  var builder=new UriBuilder(new Uri(baseUri,"api/measures/component")){Query=$"metricKeys={Uri.EscapeDataString(Metrics)}&component={Uri.EscapeDataString(request.ProjectKey)}"};
  using var message=new HttpRequestMessage(HttpMethod.Get,builder.Uri);message.Headers.Authorization=new AuthenticationHeaderValue("Bearer",request.Token);
  HttpResponseMessage response;try{response=await client.SendAsync(message,HttpCompletionOption.ResponseHeadersRead,ct);}catch(OperationCanceledException)when(!ct.IsCancellationRequested){return CodeQualityProviderResult.Fail("quality_timeout","SonarQube did not respond in time.",ProjectQualityState.TemporarilyUnavailable);}catch(HttpRequestException){return CodeQualityProviderResult.Fail("quality_unavailable","SonarQube is temporarily unavailable.",ProjectQualityState.TemporarilyUnavailable);}
  using(response){if((int)response.StatusCode is >=300 and <400)return CodeQualityProviderResult.Fail("quality_redirect_rejected","SonarQube returned an unexpected redirect.",ProjectQualityState.Failed);if(response.StatusCode is HttpStatusCode.Unauthorized or HttpStatusCode.Forbidden)return CodeQualityProviderResult.Fail("quality_authentication_required","SonarQube authentication or Browse permission is required.",ProjectQualityState.AuthenticationRequired);if(response.StatusCode==HttpStatusCode.NotFound)return CodeQualityProviderResult.Fail("quality_project_not_found","The configured SonarQube project was not found.",ProjectQualityState.ProjectNotFound);if(response.StatusCode==(HttpStatusCode)429||(int)response.StatusCode>=500)return CodeQualityProviderResult.Fail("quality_temporarily_unavailable","SonarQube is temporarily unavailable.",ProjectQualityState.TemporarilyUnavailable);if(!response.IsSuccessStatusCode)return CodeQualityProviderResult.Fail("quality_request_failed","SonarQube rejected the quality request.",ProjectQualityState.Failed);try{await using var stream=await response.Content.ReadAsStreamAsync(ct);using var json=await JsonDocument.ParseAsync(stream,cancellationToken:ct);var measures=json.RootElement.GetProperty("component").GetProperty("measures").EnumerateArray().Where(x=>x.TryGetProperty("metric",out var metric)&&metric.ValueKind==JsonValueKind.String&&x.TryGetProperty("value",out var value)&&value.ValueKind==JsonValueKind.String).GroupBy(x=>x.GetProperty("metric").GetString()!,StringComparer.Ordinal).ToDictionary(x=>x.Key,x=>x.Last().GetProperty("value").GetString(),StringComparer.Ordinal);var gate=Text(measures,"alert_status");var state=gate is null?ProjectQualityState.Available:gate.Equals("OK",StringComparison.OrdinalIgnoreCase)?ProjectQualityState.Passed:ProjectQualityState.Failed;var projectUrl=new Uri(baseUri,$"dashboard?id={Uri.EscapeDataString(request.ProjectKey)}").ToString();return CodeQualityProviderResult.Ok(new(state,gate,Metric(measures,"coverage"),Metric(measures,"new_coverage"),Metric(measures,"bugs"),Metric(measures,"vulnerabilities"),Metric(measures,"code_smells"),Rating(measures,"reliability_rating"),Rating(measures,"security_rating"),Rating(measures,"sqale_rating"),Metric(measures,"duplicated_lines_density"),Metric(measures,"ncloc"),Metric(measures,"cognitive_complexity"),null,null,null,projectUrl));}catch(Exception exception)when(exception is JsonException or InvalidOperationException or KeyNotFoundException){return CodeQualityProviderResult.Fail("quality_response_invalid","SonarQube returned an invalid measures response.",ProjectQualityState.TemporarilyUnavailable);}}
 }
 private static string? Text(Dictionary<string,string?> values,string key)=>values.GetValueOrDefault(key);
 private static QualityMetric Metric(Dictionary<string,string?> values,string key)=>decimal.TryParse(Text(values,key),NumberStyles.Float,CultureInfo.InvariantCulture,out var value)?new(value):new(null);
 private static QualityMetric Rating(Dictionary<string,string?> values,string key){var raw=Text(values,key);if(!decimal.TryParse(raw,NumberStyles.Float,CultureInfo.InvariantCulture,out var value))return new(null);var rating=value switch{1=>"A",2=>"B",3=>"C",4=>"D",5=>"E",_=>"Unknown"};return new(value,rating);}
 private static Uri EnsureTrailingSlash(Uri uri)=>uri.AbsoluteUri.EndsWith('/')?uri:new(uri.AbsoluteUri+"/",UriKind.Absolute);
}
